#  Copyright (c) 1990-1994 The Regents of the University of California.
#  Copyright (c) 1994-1996 Sun Microsystems, Inc.
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#

=head1 NAME

Tk::tkvars - Variables used or set by Tk

=for category  Tk Generic Methods

=head1 DESCRIPTION

The following perl variables are either set or used by Tk at various times
in its execution. (For a list of variables used by perl see L<perlvar>.)

=over 4

=item B<$Tk::library>

This variable holds the file name for a directory containing the modules
related to Tk.  These modules include an initialization
file that is normally processed whenever a Tk application starts up,
plus other files containing procedures that implement default behaviors
for widgets.
The initial value of B<$Tk::library> is set when Tk is added to
an interpreter;  this is done by searching searching for a directory
named Tk in the directory where the file F<Tk.pm>, or the first
directory F<Tk> in C<@INC>.

The B<TK_LIBRARY> environment variable used by Tcl/Tk is not
supported by perl/Tk.  Please use L<@INC|perlvar/@INC> to change where modules
are searched.

B<Note:> This is Tcl remnant. With perl it makes more sense to
use C<@INC> and C<%INC>).

=item B<$Tk::patchLevel>

Contains a decimal integer giving the current patch level for Tk.
The patch level is incremented for each new release or patch, and
it uniquely identifies an official version of Tk.

B<Note:> this is Tcl remnant. With perl it makes more sense to
use B<$Tk::VERSION> described below.

=item B<$Tk::strictMotif>

This variable is set to zero by default.
If an application sets it to one, then Tk attempts to adhere as
closely as possible to Motif look-and-feel standards.
For example, active elements such as buttons and scrollbar
sliders will not change color when the pointer passes over them.

=item B<$Tk::VERSION>

The variable holds the current version number of the perl/Tk
release in the form I<major>.I<minor>.  I<Major> and
I<minor> are integers.

The I<major> version number shows on which
Tcl/Tk release perl/Tk is based.  E.g., B<402> means based on
Tcls Tk 4.2.  (Patchlevel of Tcls Tk are not incorporated because
perl/Tk tended  to be ``I<ahead>'' of them on some fixes and behind on
others.  The first digest of the major version number increases in
any Tk release that includes changes that are not backward compatible
(i.e. whenever existing perl/Tk applications and scripts may have to change to
work with the new release).

The I<minor> version depends on perl/Tk only. It uses the
'even'='stable', 'odd'='experimental' scheme that linux uses:

 .0xx  - inherently 'alpha'
 .1xx  - experimental 'beta'
 .2xx  - stable
 .3xx  - experimental
 .4xx  - stable
 ...

The minor version number increases with
each new release of Tk, except that it resets to zero whenever the
major version number changes.

=item B<$Tk::version>

The variable holds the current version number of the Tk
library in the form I<major>.I<minor>.  I<Major> and
I<minor> are integers.  The major version number increases in
any Tk release that includes changes that are not backward compatible
(i.e. whenever existing Tk applications and scripts may have to change to
work with the new release).  The minor version number increases with
each new release of Tk, except that it resets to zero whenever the
major version number changes.

B<Note:> this is Tcl remnant.  With perl it makes more sense to
use B<$Tk::VERSION> described above.

=back

=head1 KEYWORDS

variables, version

=cut

