#!/bin/sh
# postinst config of McStas
echo Configuring McStas
cd /usr/local/lib/mcstas
mcdoc --text
cd /usr/local/lib/mcstas/tools/perl/
./mcstas_reconfigure
echo Install entry in Applications menu
cp /usr/local/lib/mcstas/tools/McStas.desktop /usr/share/applications/
echo Instal gedit/kate preferences for syntax highlight
if [ -d /usr/share/gtksourceview-1.0/ ]; then \
  cp /usr/local/lib/mcstas/editors/mcstas1.lang /usr/share/gtksourceview-1.0/language-specs/;
fi;
if [ -d /usr/share/gtksourceview-2.0/ ]; then \
  cp /usr/local/lib/mcstas/editors/mcstas2.lang /usr/share/gtksourceview-2.0/language-specs/;
fi;
if [ -d /usr/share/apps/katepart/syntax/ ]; then \
  cp /usr/local/lib/mcstas/editors/mcstas.xml /usr/share/apps/katepart/syntax/;
fi;
