#!/bin/sh
#
# Wrapper for sed to replace version numbering in mcstas components, etc.
#
# PW, risoe, Jan. 2003
sed 's/Release: McStas 1.6/Release: McStas '$2'/' $1 > $1.tmp
cat $1.tmp > $1
rm -f $1.tmp
