#!/bin/sh
# Extract documentation from pgplot source code: output VMS help file
cat << \EOD
1 PGPLOT
  PGPLOT GRAPHICS SUBROUTINE LIBRARY Version 5.2

  PGPLOT is a Fortran subroutine package for drawing graphs on a variety
  of display devices. For more details, see the manual ``PGPLOT Graphics
  Subroutine Library'' available from T. J. Pearson
  (tjp@astro.caltech.edu).

  Arguments
 
  The subroutine descriptions indicate the data type of each argument.
  When arguments are described as ``input'', they may be replaced with
  constants or expressions in the CALL statement, but make sure that the
  constant or expression has the correct data type.
   
  INTEGER arguments:
     these should be declared INTEGER or INTEGER*4 in the calling
     program, not INTEGER*2.
          
  REAL arguments:
     these should be declared REAL or REAL*4 in the calling program,
     not REAL*8 or DOUBLE PRECISION.
          
  LOGICAL arguments:
     these should be declared LOGICAL or LOGICAL*4 in the calling
     program.
          
  CHARACTER arguments:
     any valid Fortran CHARACTER variable may be used (declared
     CHARACTER*n for some integer n).
EOD
awk '
/^C\*/ { print "";
         print "2 " substr($0, 3, 500);
       }
/^C\+/ { echo = 1; getline }
/^C--/ { echo = 0}

echo == 1 && /^C/ {print "  " substr($0, 3, 500) }

echo == 1 && !/^C/ { print }
' $*

