#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated

./3rdparty/sync.sh

# 64-bit
./mkdist mcxtrace $1 "" "" linux64 "" -- src bin
./mkdist mcxtrace-comps $1 "" "" linux64 "" -- src bin
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mccodelib $1 tools/Python/mccodelib/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" linux64 "" -- src bin
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" linux64 "" -- src bin
./mkdist mcxtrace-miniconda3 $1 support/rpm/miniconda3/ "" linux64 "" -- src bin
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" linux64 "" -- src bin
./mkdist mcxtrace-manuals $1 doc/manuals/mcxtrace/ "" linux64 "o" -- src bin

#build metapackages?
if [ "x$2" != "x" ]; then
  cd meta-pkgs/src

  outfile=mcxtrace-${1}-UNIX-src.tar
  if [ -e $outfile ]; then
    rm $outfile;
  fi
  if [ -e ${outfile}.gz ]; then
    rm ${outfile}.gz;
  fi

  ln -s ../../dist ${outfile%.tar}
  echo  ${outfile%.tar}

  for subpkg in `ls ${outfile%.tar}/mcxtrace*-${1}-src.tar.gz`
  do
    tar -h -rf $outfile $subpkg
  done
  tar -tf $outfile
  gzip $outfile
  rm mcxtrace-${1}-UNIX-src
fi
