#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit Mac OS
./mkdist mcxtrace $1 "" "" mac_SL -- OSXpkg
./mkdist mcxtrace-comps $1 "" "" mac_SL -- OSXpkg
./mkdist mcxtrace-tools-Perl $1 tools/Legacy-Perl/ "" mac_SL -- OSXpkg
./mkdist mcxtrace-tools-Python-mxplot-chaco $1 tools/Python/mcplot/chaco/ "" mac_SL -- OSXpkg
./mkdist mcxtrace-tools-Python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac_SL -- OSXpkg
./mkdist mcxtrace-tools-Python-mxrun $1 tools/Python/mcrun/ "" mac_SL -- OSXpkg
./mkdist mcxtrace-tools-Python-mxdisplay $1 tools/Python/mcdisplay/x3d/ "" mac_SL -- OSXpkg
