#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit
./mkdist mcxtrace $1 "" "" linux64 -- rpm
./mkdist mcxtrace-comps $1 "" "" linux64 -- rpm
./mkdist mcxtrace-tools-Perl $1 tools/Legacy-Perl/ "" linux64 -- rpm
./mkdist mcxtrace-tools-Python-mxplot-chaco $1 tools/Python/mcplot/chaco/ "" linux64 -- rpm
./mkdist mcxtrace-tools-Python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux64 -- rpm
./mkdist mcxtrace-tools-Python-mxrun $1 tools/Python/mcrun/ "" linux64 -- rpm
./mkdist mcxtrace-tools-Python-mxdisplay $1 tools/Python/mxdisplay/x3d/ "" linux64 -- rpm

# 32-bit
./mkdist mcxtrace $1 "" "" linux32 -- rpm
./mkdist mcxtrace-comps $1 "" "" linux32 -- rpm
./mkdist mcxtrace-tools-Perl $1 tools/Legacy-Perl/ "" linux32 -- rpm
./mkdist mcxtrace-tools-Python-mxplot-chaco $1 tools/Python/mcplot/chaco/ "" linux32 -- rpm
./mkdist mcxtrace-tools-Python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux32 -- rpm
./mkdist mcxtrace-tools-Python-mxrun $1 tools/Python/mcrun/ "" linux32 -- rpm
./mkdist mcxtrace-tools-Python-mxdisplay $1 tools/Python/mxdisplay/x3d/ "" linux32 -- rpm
