#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# This is an app bundle being built, relocatable.
export MCINSTALL_PREFIX=/Applications/McXtrace-$1.app/
./mkdist mcxtrace-app $1 support/MacOSX/McCode.app/ "" mac "" -- OSXapp

# For the actual mcstas part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McXtrace-$1.app/Contents/Resources/
# 64-bit Mac OS
./mkdist mcxtrace $1 "" "" mac "" -- OSXapp
./mkdist mcxtrace-comps $1 "" "" mac "" -- OSXapp
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mcodelib $1 tools/Python/mccodelib/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" mac "" -- OSXapp

# Download and embed a miniconda
echo
echo "*********************************************************"
echo "* Downloading and embeeding miniconda3 in your app      *"
echo "*********************************************************"
echo   
sleep 3
curl -O https://repo.continuum.io/miniconda/Miniconda3-4.2.12-MacOSX-x86_64.sh
chmod a+x Miniconda3-4.2.12-MacOSX-x86_64.sh
./Miniconda3-4.2.12-MacOSX-x86_64.sh -b -p $MCINSTALL_PREFIX/miniconda3/

# Run conda to install the dependencies
echo
echo "*********************************************************"
echo "* Downloading python dependencies to embedded miniconda *"
echo "*********************************************************"
echo 
$MCINSTALL_PREFIX/miniconda3/bin/conda config --add channels conda-forge
$MCINSTALL_PREFIX/miniconda3/bin/conda install python=3.4 pyqt=4.11.4 qscintilla2 pyqtgraph pyaml gcc openmpi ply -y -c conda-forge

# Copy in the mpicc snippets
cp support/MacOSX/mpicc-wrappers/* $MCINSTALL_PREFIX/mcxtrace/$1/bin

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McXtrace-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McXtrace-$1.app/Contents/Resources/mcxtrace/$1/environment McXtrace-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    mv dist mcxtrace-$1
    mkdir dist
    tar cfz dist/mcxtrace-$1.tgz mcxtrace-$1
    echo A tgz of your app is now located in the dist folder
    rm -rf mcxtrace-$1
else
    ln -s /Applications/McXtrace-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



