#!/bin/sh

PATH=$PATH:$PWD/tools/download-tool

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Workaround for having CRLF linefeeds in a couple of windows packages
rsync -avz --delete --exclude=".svn/" mcxtrace-comps/ mcxtrace-comps-win
find mcxtrace-comps-win -type f -not -name \*.off -exec todos \{\} \;
rsync -avz --delete --exclude=".svn/" tools/Legacy-Perl/ tools/Legacy-Perl-win
rsync -avz --delete --exclude=".svn/" tools/Legacy-Perl-cmdline/ tools/Legacy-Perl-cmdline-win
find tools/Legacy-Perl-win -type f -exec todos \{\} \;
find tools/Legacy-Perl-cmdline-win -type f -exec todos \{\} \;

# 32-bit
./mkdist mcxtrace $1 "" "" mingw32 "" -- nsis
./mkdist mcxtrace-comps $1 "" "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl-win/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline-win/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mingw32 "" -- nsis
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" mingw32 "" -- nsis
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" mingw32 "o" -- nsis

if [ "x$2" != "x" ]; then
    # Build the meta-packages also
    cd meta-pkgs/windows/Support
    if [ ! -f PPDs.zip ]; then
	wget http://ppds.mccode.org/PPDs.zip
    fi
    if [ ! -f Miniconda3-latest-Windows-x86.exe ]; then
	echo Sorry! I need to download a Miniconda3 for embedding - will take some time...
	wget https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe
    fi
    cd ..

    sed s/@VERSION@/${1}/g python-install.bat.in > python-install.bat.in.2
    sed s/@FLAVOR@/mcstas/g python-install.bat.in.2 > python-install.bat
    sed s/@VERSION@/${1}/g McXtrace-metapackage32.iss > McXtrace-${1}-metapackage32.iss
    ./iscc McXtrace-${1}-metapackage32.iss
    mv Output/setup.exe dist/McXtrace-Metapackage-${1}-win32.exe
    mkdir dist/extras
    cp MSMPI/*.* dist/extras
    cp NeXus/*.* dist/extras
fi
