#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit
./mkdist mcstas $1 "" "" linux64 "" -- rpm
./mkdist mcstas-comps $1 "" "" linux64 "" -- rpm
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" linux64 "" -- rpm
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcplot-gnuplot $1 tools/Python/mcplot/gnuplot/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-r $1 tools/Python/mcdisplay/R/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" linux64 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-vtk $1 tools/Python/mcdisplay/VTK/ "" linux64 "" -- rpm
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" linux64 "o" -- rpm

# 32-bit
./mkdist mcstas $1 "" "" linux32 "" -- rpm
./mkdist mcstas-comps $1 "" "" linux32 "" -- rpm
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" linux32 "" -- rpm
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcplot-gnuplot $1 tools/Python/mcplot/gnuplot/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-r $1 tools/Python/mcdisplay/R/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" linux32 "" -- rpm
./mkdist mcstas-tools-python-mcdisplay-vtk $1 tools/Python/mcdisplay/VTK/ "" linux32 "" -- rpm
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" linux32 "o" -- rpm
