#!/bin/sh

PATH=$PATH:$PWD/tools/download-tool

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Workaround for having CRLF linefeeds in a couple of windows packages
rsync -avz --delete --exclude=".svn/" mcxtrace-comps/ mcxtrace-comps-win
find mcxtrace-comps-win -type f -not -name \*.off -exec todos \{\} \;
rsync -avz --delete --exclude=".svn/" tools/Legacy-Perl/ tools/Legacy-Perl-win
find tools/Legacy-Perl-win -type f -exec todos \{\} \;

# 32-bit
./mkdist mcxtrace $1 "" "" mingw32 "" -- nsis
./mkdist mcxtrace-comps $1 "" "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mingw32 "" -- nsis
./mkdist mcxtrace-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mingw32 "" -- nsis
./mkdist mcxtrace-manuals $1 doc/manuals/mcxtrace/ "" mingw32 "o" -- nsis

if [ "x$2" != "x" ]; then
    # Build the meta-packages also
    cd meta-pkgs/windows/Support
    if [ ! -f PPDs.zip ]; then
	wget http://ppds.mccode.org/PPDs.zip
    fi
    cd ..

    sed s/@VERSION@/${1}/g McXtrace-metapackage32.iss > McXtrace-${1}-metapackage32.iss
    ./iscc McXtrace-${1}-metapackage32.iss
    mv Output/setup.exe dist/McXtrace-Metapackage-${1}-win32.exe

fi
