#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated
THIRDPARTY=`ls 3rdparty | grep -v patches`
cd 3rdparty

cd -

./3rdparty/sync.sh


for MODULE in `echo $THIRDPARTY`
do
    if [ -d "3rdparty/patches/${MODULE}" ]; then
	echo Making McCode cmake modules available for $MODULE
        rsync -avz cmake/ 3rdparty/${MODULE}/cmake
	echo Applying McCode patches to 3rdparty/${MODULE}
	cp -rp 3rdparty/patches/${MODULE}/* 3rdparty/${MODULE}/
    fi
done

# This is an app bundle being built, but non-relocatable.
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/
./mkdist mcstas-app $1 support/MacOSX/McCode.app/ "" mac-silicon "" -- OSXapp
# hack to ensure the silicon app is opened arch -arm64
sed -i.bak s+/bin/bash+/usr/bin/arch\ -arm64\ /bin/bash+ $MCINSTALL_PREFIX/Contents/MacOS/mccodegui

# For the actual mcstas part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/
# 64-bit Mac OS
./mkdist mcstas $1 "" "" mac-silicon "" -- OSXapp
./mkdist mcstas-comps $1 "" "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-matlab-mcdisplay $1 tools/matlab/mcdisplay/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-svg $1 tools/Python/mcplot/svg/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcresplot $1 tools/Python/mcresplot/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-mantid $1 tools/Python/mcdisplay/mantid_xml/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-tools-python-mcdoc $1 tools/Python/mcdoc/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-clusterscripts $1 tools/cluster-scripts/ "" mac-silicon "" -- OSXapp
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" mac-silicon "" -- OSXapp

WORK=`pwd`

# NCrystal installation:
rm -rf 3rdparty/ncrystal/build
mkdir 3rdparty/ncrystal/build
cd 3rdparty/ncrystal/build
cmake .. -DCMAKE_INSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/ -DBUILD_G4HOOKS=OFF
make
make install
cd $WORK
rm -rf 3rdparty/ncrystal/build

# Hack to ensure pymcpltool is in place
ln -s /Applications/McStas-$1.app/Contents/Resources/mcstas/$1/libs/mcpl/pymcpltool /Applications/McStas-$1.app/Contents/Resources/mcstas/$1/bin

# Copy in the mpicc snippets
cp support/MacOSX/mpicc-wrappers/* $MCINSTALL_PREFIX/mcstas/$1/bin

export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/

cd $WORK
# Generate mcdoc pages
python3 $MCINSTALL_PREFIX/mcstas/$1/tools/Python/mcdoc/mcdoc.py -i

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McStas-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McStas-$1.app/Contents/Resources/mcstas/$1/environment McStas-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    cp support/MacOSX/silicon-homebrew-setup/* dist
    mv dist mcstas-$1
    mkdir dist
    tar cfz dist/mcstas-$1_arm64.tgz mcstas-$1
    cp INSTALL-McStas-3.x/macOS/README.md dist
    echo A tgz of your app is now located in the dist folder
    rm -rf mcstas-$1
else
    ln -s /Applications/McStas-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



