#!/bin/sh
#
# Script for cleaning up old selftest_ directories from mcrun / mxrun --test across a set of virtual machines
#
# Requirements - like those of the 'nightly' script
#

# Cd to SVN area on buildfarm-master
cd /Users/mccode/McCode/trunk

WINHOST=172.16.97.10
LINHOST=172.16.97.11
OSXHOST=localhost

WINUSER=mcstas
LINUSER=mccode
OSXUSER=mccode

echo Clean out selftest dirs on the hosts
# Build the Linux (deb) and Windows packages at the Linux host
# Step 0 - cleanup
ssh ${LINUSER}@${LINHOST} rm -rf selftest_\*
ssh ${OSXUSER}@${OSXHOST} rm -rf selftest_\*

ssh ${WINUSER}@${WINHOST} for /d %a in \(selftest*\) do rd /s /q %a

wait
echo Done cleaning...
