#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit Mac OS
./mkdist mcstas $1 "" "" mac_SL -- OSXpkg
./mkdist mcstas-comps $1 "" "" mac_SL -- OSXpkg
./mkdist mcstas-tools-Perl $1 tools/Legacy-Perl/ "" mac_SL -- OSXpkg
./mkdist mcstas-tools-Python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" mac_SL -- OSXpkg
./mkdist mcstas-tools-Python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac_SL -- OSXpkg
./mkdist mcstas-tools-Python-mcrun $1 tools/Python/mcrun/ "" mac_SL -- OSXpkg
./mkdist mcstas-tools-Python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" mac -- OSXpkg
./mkdist mcstas-tools-Python-mcdisplay-r $1 tools/Python/mcdisplay/R/ "" mac -- OSXpkg
./mkdist mcstas-tools-Python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" mac -- OSXpkg
./mkdist mcstas-tools-Python-mcdisplay-vtk $1 tools/Python/mcdisplay/VTK/ "" mac -- OSXpkg
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" mac -- OSXpkg
