#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated

./3rdparty/sync.sh

./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" noarch "o" -- NONE 
echo
echo LaTeX build of McStas manuals v $1 done!
echo
cp dist/mcstas-manuals-$1-noarch-not-packaged.work/*pdf docpkg/manuals/mcstas
echo
echo Consider doing a git commit for the PDF files in docpkg/manuals/mcstas, as these have now been updated:
git status docpkg/manuals/mcstas
