#!/bin/sh

PATH=$PATH:$PWD/tools/download-tool

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Workaround for having CRLF linefeeds in a couple of windows packages
rsync -avz --delete --exclude=".svn/" mcstas-comps/ mcstas-comps-win
find mcstas-comps-win -type f -not -name \*.off -exec todos \{\} \;
rsync -avz --delete --exclude=".svn/" tools/Legacy-Perl/ tools/Legacy-Perl-win
find tools/Legacy-Perl-win -type f -exec todos \{\} \;

# 32-bit
./mkdist mcstas $1 "" "" mingw32 "" -- nsis
./mkdist mcstas-comps $1 mcstas-comps-win "" mingw32 "" -- nsis
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl-win "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcplot-gnuplot $1 tools/Python/mcplot/gnuplot/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcdisplay-r $1 tools/Python/mcdisplay/R/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" mingw32 "" -- nsis
./mkdist mcstas-tools-python-mcdisplay-vtk $1 tools/Python/mcdisplay/VTK/ "" mingw32 "" -- nsis
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" mingw32 "o" -- nsis

if [ "x$2" != "x" ]; then
    # Build the meta-packages also
    cd meta-pkgs/windows/Support
    if [ ! -f PPDs.zip ]; then
	wget http://ppds.mccode.org/PPDs.zip
    fi
    cd ..

    sed s/@VERSION@/${1}/g McStas-metapackage32.iss > McStas-${1}-metapackage32.iss
    ./iscc McStas-${1}-metapackage32.iss
    mv Output/setup.exe dist/McStas-Metapackage-${1}-win32.exe
fi
