#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# From 1.2 onwards, let McXtrace reside in /usr/share on Debian-like systems
export MCINSTALL_PREFIX=/usr/share/

# 32-bit
./mkdist mcxtrace $1 "" "" armlinux32 "" -- deb
./mkdist mcxtrace-comps $1 "" "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-python-mxplot-chaco $1 tools/Python/mcplot/chaco/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" armlinux32 "" -- deb
./mkdist mcxtrace-tools-python-mxdisplay $1 tools/Python/mcdisplay/x3d/ "" armlinux32 "" -- deb
./mkdist mcxtrace-manuals $1 doc/manuals/mcxtrace/ "" armlinux32 "o" -- deb
