#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

./build_manuals_mcstas $1
./build_debs_mcstas $1 meta
./build_rpms_mcstas $1 meta
./build_src_bin_mcstas $1
./build_windows_mcstas $1 meta
