#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# This is an app bundle being built, relocatable.
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/
./mkdist mcstas-app $1 support/MacOSX/McCode.app/ "" mac "" -- OSXapp

# For the actual mcstas part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/
# 64-bit Mac OS
./mkdist mcstas $1 "" "" mac "" -- OSXapp
./mkdist mcstas-comps $1 "" "" mac "" -- OSXapp
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac "" -- OSXapp
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" mac "" -- OSXapp

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McStas-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McStas-$1.app/Contents/Resources/mcstas/$1/environment McStas-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    mv dist mcstas-$1
    mkdir dist
    tar cfz dist/mcstas-$1.tgz mcstas-$1
    echo A tgz of your app is now located in the dist folder
    rm -rf mcstas-$1
else
    ln -s /Applications/McStas-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



