#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit
./mkdist mcstas $1 "" "" linux64 "" -- src bin
./mkdist mcstas-comps $1 "" "" linux64 "" -- src bin
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" linux64 "" -- src bin
./mkdist mcstas-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" linux64 "" -- src bin
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcplot-svg $1 tools/Python/mcplot/svg/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" linux64 "" -- src bin
./mkdist mcstas-tools-python-mcdisplay-mantid $1 tools/Python/mcdisplay/mantid_xml/ "" linux64 "" -- src bin
./mkdist mcstas-miniconda3 $1 support/rpm/miniconda3/ "" linux64 "" -- src bin
./mkdist mcstas-clusterscripts $1 tools/cluster-scripts/ "" linux64 "" -- src bin
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" linux64 "" -- src bin

#build metapackages?
if [ "x$2" != "x" ]; then
  cd meta-pkgs/src

  outfile=mcstas-${1}-UNIX-src.tar
  if [ -e $outfile ]; then
    rm $outfile;
  fi
  if [ -e ${outfile}.gz ]; then
    rm ${outfile}.gz;
  fi

  ln -s ../../dist ${outfile%.tar}
  echo  ${outfile%.tar}

  for subpkg in `ls ${outfile%.tar}/mcstas*-${1}-src.tar.gz`
  do
    tar -h -rf $outfile $subpkg
  done
  tar -tf $outfile
  gzip $outfile
  rm mcstas-${1}-UNIX-src
fi
