#!/bin/sh
echo 
echo apt-get\'ing the dependencies using sudo:
echo
sudo apt-get -y install git cmake gcc gfortran mingw-w64 gfortran-mingw-w64 flex bison build-essential mingw-w64-x86-64-dev wine64 dos2unix nsis

mkdir /tmp/innosetup  
cd /tmp/innosetup  
wget http://files.jrsoftware.org/ispack/innosetup-qsp-5.6.1.exe
wine ./innosetup-qsp-5.6.1.exe /VERYSILENT /SUPPRESMSGBOXES
