#!/bin/sh
echo 
echo DNF\'ing runtime dependencies using sudo:
echo
#setup epel-release & update
sudo dnf -y install epel-release
sudo dnf update
sudo dnf upgrade

sudo dnf -y groupinstall 'Development Tools'
sudo dnf install -y gcc-gfortran gsl-devel 
sudo dnf install -y perl-Tk perl-PDL pgplot pgplot-devel libtk-codetext-perl
#sudo dnf install -y cmake3 perl-Extuils-Makemaker
#sudo ln -sf /bin/cmake3 /usr/bin/cmake
#sudo ln -sf /bin/cpack3 /usr/bin/cpack

