#!/bin/sh

VER=svn_`date "+%Y-%m-%d"`

WINHOST=192.168.33.161
LINHOST=debian.local
OSXHOST=localhost

WINUSER=mcstas0
LINUSER=mcstas
OSXUSER=willend

LINPATH=trunk
OSXPATH=Projects/McCode/trunk

# Build the Linux (deb) and Windows packages at the Linux host

# Step 0 - cleanup
ssh ${LINUSER}@${LINHOST} cd ${LINPATH} \&\& rm -rf dist 
# Step 1 - McStas
ssh ${LINUSER}@${LINHOST} cd ${LINPATH} \&\& svn update \&\& ./build_debs_mcstas ${VER} \&\& ./build_windows_mcstas ${VER} 
# Step 2 - McXtrace
ssh ${LINUSER}@${LINHOST} cd ${LINPATH} \&\& ./build_debs_mcxtrace ${VER} \&\& ./build_windows_mcxtrace ${VER}
# Step 3 Install McStas & McXtrace
ssh ${LINUSER}@${LINHOST} cd ${LINPATH}/dist \&\& sudo dpkg -i mcstas-${VER}-linux64.deb mcstas-comps-${VER}-linux64.deb mcstas-tools-perl-${VER}-linux64.deb 
ssh ${LINUSER}@${LINHOST} cd ${LINPATH}/dist \&\& sudo dpkg -i mcxtrace-${VER}-linux64.deb mcxtrace-comps-${VER}-linux64.deb mcxtrace-tools-perl-${VER}-linux64.deb 
# Step 4 Transfer .exes to the Windows host
scp ${LINUSER}@${LINHOST}:${LINPATH}/dist/\*${VER}\*32.exe ${WINUSER}@${WINHOST}:Downloads/
# Step 5 install .exes on the Windows host


# Build the OSX packages at the Mac host
# Step 0 - cleanup
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH} \&\& rm -rf dist 
# Step 1 - McStas
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH} \&\& svn update \&\& ./build_macos_mcstas ${VER} 
# Step 2 - McXtrace
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH} \&\& ./build_macos_mcxtrace ${VER} 
# Step 3 Install McStas & McXtrace
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcstas-OSXpkg-${VER}\*.pkg -target /
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcstas-comps-OSXpkg-${VER}\*.pkg -target /
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcstas-tools-perl-OSXpkg-${VER}\*.pkg -target /
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcxtrace-OSXpkg-${VER}\*.pkg -target /
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcxtrace-comps-OSXpkg-${VER}\*.pkg -target /
ssh ${OSXUSER}@${OSXHOST} cd ${OSXPATH}/dist \&\& sudo installer -pkg mcxtrace-tools-perl-OSXpkg-${VER}\*.pkg -target /
