#!/bin/sh
#
# Wrapper for sed to replace copyright strings
#
# PW, risoe, Mar. 2006
#
#   This file is part of the McStas neutron ray-trace simulation package
#   Copyright (C) 1997-2006, All rights reserved
#   Risoe National Laborartory, Roskilde, Denmark
#   Institut Laue Langevin, Grenoble, France
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; version 2 of the License.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


YEAR=`date +%Y`
sed 's/Copyright (C) 1997-..../Copyright (C) 1997-'$YEAR'/' $1 > $1.tmp
cat $1.tmp > $1
rm -f $1.tmp
sed 's/Copyright 1997-..../Copyright (C) 1997-'$YEAR'/' $1 > $1.tmp
cat $1.tmp > $1
rm -f $1.tmp
sed 's/Copyright (C) Risoe National Laboratory, 1997-..../Copyright (C) Risoe National Laboratory, 1997-'$YEAR'/' $1 > $1.tmp
cat $1.tmp > $1
rm -f $1.tmp
sed 's/Additions (C) Institut Laue Langevin, 2003-..../Additions (C) Institut Laue Langevin, 2003-'$YEAR'/' $1 > $1.tmp
cat $1.tmp > $1
rm -f $1.tmp
