#!/bin/sh

PKG_PREFIX=${PKG_PREFIX:-/usr/local}

if [ $# -ne 2 ]; then
    echo "usage: $0 distname { DEINSTALL | POST-DEINSTALL }" >&2
    exit 1
fi

execs="mcdaemon mcdisplay mcdoc mcformatgui mcgui mcplot mcresplot mcrun mcstas2vitess"

case $2 in
     DEINSTALL)
		if [ ! -f "${PKG_PREFIX}/bin" ]; then
			echo "Deinstalling links to executables in ${PKG_PREFIX}/bin.";
                        for target in ${execs}; do
				rm -rf ${PKG_PREFIX}/bin/${target};
			done                
		fi
		;;
esac

exit 0
