# -*- mode: ruby -*-
# vi: set ft=ruby :

HOST_NAME = "Debian10-McXtrace"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  #Debian 9 Stretch
  config.vm.box = "generic/debian10"
  #config.vm.define HOST_NAME do |h|
  #config.vbguest.auto_update = true
  #end

  # This is the hostname that the virtual machine uses internally.
  config.vm.hostname = HOST_NAME
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = HOST_NAME
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    #vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end

  # Install a desktop and virtualbox additions and all of the rest
  # Take one provision file at the time.
  # Do the loop:
  # terminal: vagrant up --provision 
  # Check install packages
  # terminal: vagrant halt
  # Comment in the appropriate lines

  # For McXtrace 
  # Use 1. 
  # Use 2. 
  # Use 4. 

  # 1.
  #config.vm.provision "shell", path: "provision/bootstrap.sh"
  # 2.
  #config.vm.provision "shell", path: "provision/developer.sh"
  # 3. 
  #config.vm.provision "shell", path: "provision/deps.sh"  
  # 4.
  config.vm.provision "shell", path: "provision/mcxtrace.sh"
end
