#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit
./mkdist mcstas $1 "" "" mingw64 -- nsis
./mkdist mcstas-comps $1 "" "" mingw64 -- nsis
./mkdist mcstas-tools-Perl $1 tools/Legacy-Perl/ "" mingw64 -- nsis
./mkdist mcstas-tools-Python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" mingw64 -- nsis
./mkdist mcstas-tools-Python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mingw64 -- nsis
./mkdist mcstas-tools-Python-mcrun $1 tools/Python/mcrun/ "" mingw64 -- nsis
./mkdist mcstas-tools-Python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" mingw64 -- nsis

# 32-bit
./mkdist mcstas $1 "" "" mingw32 -- nsis
./mkdist mcstas-comps $1 "" "" mingw32 -- nsis
./mkdist mcstas-tools-Perl $1 tools/Legacy-Perl/ "" mingw32 -- nsis
./mkdist mcstas-tools-Python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" mingw32 -- nsis
./mkdist mcstas-tools-Python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mingw32 -- nsis
./mkdist mcstas-tools-Python-mcrun $1 tools/Python/mcrun/ "" mingw32 -- nsis
./mkdist mcstas-tools-Python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" mingw32 -- nsis

if [ "x$2" != "x" ]; then
    # Build the meta-packages also
    cd meta-pkgs/windows

    sed s/@VERSION@/${1}/g McStas-metapackage32.iss > McStas-${1}-metapackage32.iss
    sed s/@VERSION@/${1}/g McStas-metapackage64.iss > McStas-${1}-metapackage64.iss
    ./iscc McStas-${1}-metapackage32.iss
    mv Output/setup.exe dist/McStas-Metapackage-Perl-${1}-win32.exe
    ./iscc McStas-${1}-metapackage64.iss
    mv Output/setup.exe dist/McStas-Metapackage-Perl-${1}-win64.exe

fi
