#!/bin/sh

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# 64-bit
./mkdist mcstas $1 "" "" linux64 -- rpm
./mkdist mcstas-comps $1 "" "" linux64 -- rpm
./mkdist mcstas-tools-Perl $1 tools/Legacy-Perl/ "" linux64 -- rpm
./mkdist mcstas-tools-Python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" linux64 -- rpm
./mkdist mcstas-tools-Python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux64 -- rpm
./mkdist mcstas-tools-Python-mcrun $1 tools/Python/mcrun/ "" linux64 -- rpm
./mkdist mcstas-tools-Python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" linux64 -- rpm
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" linux64 -- rpm

# 32-bit
./mkdist mcstas $1 "" "" linux32 -- rpm
./mkdist mcstas-comps $1 "" "" linux32 -- rpm
./mkdist mcstas-tools-Perl $1 tools/Legacy-Perl/ "" linux32 -- rpm
./mkdist mcstas-tools-Python-mcplot-chaco $1 tools/Python/mcplot/chaco/ "" linux32 -- rpm
./mkdist mcstas-tools-Python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux32 -- rpm
./mkdist mcstas-tools-Python-mcrun $1 tools/Python/mcrun/ "" linux32 -- rpm
./mkdist mcstas-tools-Python-mcdisplay $1 tools/Python/mcdisplay/x3d/ "" linux32 -- rpm
./mkdist mcstas-manuals $1 doc/manuals/mcstas/ "" linux32 -- rpm
