#!/usr/local/bin/perl -w

use Tk;
require Tk::LabEntry;

my $mw = MainWindow->new;

my $canvas_total = 'Entry Text';
my $le_t_text    = 'The Label';

$le = $mw->LabEntry(-textvariable =>\$canvas_total,
               -labelVariable => \$le_t_text,
               -labelPack => [-side => 'left']);

$le->pack(-expand => 1, -fill => 'x');

MainLoop;
