--- #YAML:1.0
name:               Tk
version:            804.032
abstract:           Tk - a Graphical User Interface Toolkit
author:
    - nick@ing-simmons.net (Nick Ing-Simmons)
license:            unrestricted
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:      0
    Test::More:  0
resources:
    repository:  http://github.com/eserte/perl-tk
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
