# -*- mode: ruby -*-
# vi: set ft=ruby :

HOST_NAME = "fedora33-McStas"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Centos 7
  config.vm.box = "generic/fedora33"
  config.vm.define HOST_NAME do |h|
  #config.vbguest.auto_update = true
  end

  # This is the hostname that the virtual machine uses internally.
  config.vm.hostname = HOST_NAME


  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.name = HOST_NAME
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end

  # Install ubuntu-desktop and virtualbox additions and all of the rest
  # Take one provision file at the time.
  # Do the loop:
  # terminal: vagrant up --provision 
  # Check install packages
  # terminal: vagrant halt
  # Comment in the appropriate lines

  # For McStas 
  # Use 1. 
  # Use 2. 
  # Use 4. 

  # 1.
  config.vm.provision "shell", path: "provision/bootstrap.sh"
  # 2.
  config.vm.provision "shell", path: "provision/developer.sh"
  # 3. 
  # config.vm.provision "shell", path: "provision/mantid_old_versions.sh"  
  # 4.
  # config.vm.provision "shell", path: "provision/mcstas.sh"
  # 5.
  # config.vm.provision "shell", path: "provision/libnexus0.sh"   
  # 6.
  #config.vm.provision "shell", path: "provision/mantid.sh"
  # 7.
  #config.vm.provision "shell", path: "provision/pyqtgraph.sh"
  # 8.
  #config.vm.provision "shell", path: "provision/mantid_dev2.sh"   
  # 9.
  #config.vm.provision "shell", path: "provision/anaconda.sh"
end
