.TH mcdoc 1  "" "McStas X.Y.Z, Month Day, Year" "USER COMMANDS"
.SH NAME
mcdoc \- documentation tool of the McStas neutron ray-trace simulation package
.SH SYNOPSIS
.B mcdoc
[\-mc] [comp|instr]
.SH DESCRIPTION
The
.B mcdoc
command is the documentation tool of the McStas package. It opens a browser to display help ressources.
.PP
.B McStas
is a general tool for simulating neutron scattering instruments and experiments. It is actively supported by
.I Risoe National Laboratory
and
.I ILL

.PP
McStas is based on a compiler [mcstas(1)] that reads a high-level specification language defining the instrument to be simulated and produces C code that performs the Monte Carlo Simulation. The system is very fast in use, both when setting up the instrument definition and when doing calculations.
.PP
McStas supports triple-axis,  time-of-flight instruments, and polarised neutrons. It comes with a comprehensive manual and a library of well-tested components that include most standard elements of neutron scattering instruments, including steady-state and pulsed sources, monochromators/analysers, guides, collimators, vanadium and powder samples, velocity selectors and choppers, and a variety of detectors.
.PP
The package consists of the following user commands:
.TP
mcgui(1)
is the graphical user interface. Then use the
.I Neutron Site
menu to select an example instrument, and access the whole documentation for the
.I Help
menu. It contains an instrument editor, methods to plot simulation results, and much more
.TP
mcrun(1)
is the command-line tool for building and running simulations
.TP
mcplot(1)
is the simulation results plotting tool
.TP
mcdisplay(1)
is the instrument geometry and neutron trajectory viewer
.TP
.B mcdoc(1)
is the documentation tool
.TP
mcstas(1)
is the instrument compiler
.TP
mcconvert(1)
can convert Matlab data files into Scilab data files, and vice-versa. It also handles data sets with binary encoding. It also handles parameter scan results.
.TP
mcformat(1)
can transform any text data set from one format to an other. It does not support conversion from binary data sets. It can also merge equivalent results.
.PP
We encourage users to refer to the User and Component Manuals, which are available with the command
.B
mcdoc
.P
.SH OPTIONS
The usage of the command does not require option. Refer to mcplot \-h for special uses.
.TP
\-h | \-\-help
displays the command help
.TP
\-c
opens the Component manual
.TP
\-m
opens the User manual
.SH EXAMPLES
.TP
Typical usage
.B mcdoc
.SH ENVIRONMENT
The
.B MCSTAS
environment variable may be set to define the McStas library location. This is /usr/local/lib/mcstas on Linux systems. Executables are usually located in /usr/local/bin.
.P
The
.B BROWSER
environment variable may be set to define the default HTML browser to use
.SH BUGS
McStas is a large package, and bugs might be found. If so, please report to
.B http://mcstas.org/McZilla/
and the mailing list
.B neutron-mc@risoe.dk
.SH AUTHOR
Peter Kjaer Willendrup, Emmanuel FARHI, Kim Lefmann, and Klaus Lieutenant
.SH SEE ALSO
mcstas(1), mcrun(1), mcdisplay(1), mcplot(1), mcgui(1), mcdoc(1), mcformat(1), mcconvert(1)
.P
web site:     <http://www.mcstas.org>
.P
mailing list: <mailto:neutron-mc@risoe.dk>
.P
matlab(1), idl(1), scilab(1), octave(1), vitess(1), NISP(1), restrax(1), mcnp(1), tripoli(1)
