# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-CodeText
version:      0.3.4
version_from: CodeText.pm
installdirs:  site
requires:
    Syntax::Highlight::Perl:       0
    Tk:                            800.024

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
