#!/usr/bin/env python
#
# Widgets for mcgnuview created with QtCreator. DO NOT EDIT.
#
from PyQt4 import QtCore, QtGui

class Ui_McGnuWindow(object):
    def setupUi(self, McGnuWindow):
        McGnuWindow.setObjectName("McGnuWindow")
        McGnuWindow.resize(397, 307)
        self.centralwidget = QtGui.QWidget(McGnuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbxMonitors = QtGui.QGroupBox(self.centralwidget)
        self.gbxMonitors.setObjectName("gbxMonitors")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbxMonitors)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstvMonitors = QtGui.QListView(self.gbxMonitors)
        self.lstvMonitors.setObjectName("lstvMonitors")
        self.verticalLayout_2.addWidget(self.lstvMonitors)
        self.horizontalLayout.addWidget(self.gbxMonitors)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxOptions = QtGui.QGroupBox(self.centralwidget)
        self.gbxOptions.setObjectName("gbxOptions")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbxOptions)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox = QtGui.QCheckBox(self.gbxOptions)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.verticalLayout.addWidget(self.gbxOptions)
        self.gbxSave = QtGui.QGroupBox(self.centralwidget)
        self.gbxSave.setObjectName("gbxSave")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxSave)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnSave_2 = QtGui.QPushButton(self.gbxSave)
        self.btnSave_2.setObjectName("btnSave_2")
        self.verticalLayout_3.addWidget(self.btnSave_2)
        self.btnSave_1 = QtGui.QPushButton(self.gbxSave)
        self.btnSave_1.setObjectName("btnSave_1")
        self.verticalLayout_3.addWidget(self.btnSave_1)
        self.btnSave_3 = QtGui.QPushButton(self.gbxSave)
        self.btnSave_3.setObjectName("btnSave_3")
        self.verticalLayout_3.addWidget(self.btnSave_3)
        self.btnSave_4 = QtGui.QPushButton(self.gbxSave)
        self.btnSave_4.setObjectName("btnSave_4")
        self.verticalLayout_3.addWidget(self.btnSave_4)
        self.btnSaveAs = QtGui.QPushButton(self.gbxSave)
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.verticalLayout_3.addWidget(self.btnSaveAs)
        self.verticalLayout.addWidget(self.gbxSave)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        McGnuWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(McGnuWindow)
        self.statusBar.setObjectName("statusBar")
        McGnuWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(McGnuWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(McGnuWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(McGnuWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPng = QtGui.QAction(McGnuWindow)
        self.actionPng.setObjectName("actionPng")
        self.actionEps = QtGui.QAction(McGnuWindow)
        self.actionEps.setObjectName("actionEps")
        self.actionPdf = QtGui.QAction(McGnuWindow)
        self.actionPdf.setObjectName("actionPdf")
        self.actionGif = QtGui.QAction(McGnuWindow)
        self.actionGif.setObjectName("actionGif")

        self.retranslateUi(McGnuWindow)
        QtCore.QMetaObject.connectSlotsByName(McGnuWindow)

    def retranslateUi(self, McGnuWindow):
        McGnuWindow.setWindowTitle(QtGui.QApplication.translate("McGnuWindow", "McGnuplot", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxMonitors.setTitle(QtGui.QApplication.translate("McGnuWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxOptions.setTitle(QtGui.QApplication.translate("McGnuWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("McGnuWindow", "Log scale (l)", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxSave.setTitle(QtGui.QApplication.translate("McGnuWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave_2.setText(QtGui.QApplication.translate("McGnuWindow", "ps", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave_1.setText(QtGui.QApplication.translate("McGnuWindow", "psc", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave_3.setText(QtGui.QApplication.translate("McGnuWindow", "gif", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave_4.setText(QtGui.QApplication.translate("McGnuWindow", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveAs.setText(QtGui.QApplication.translate("McGnuWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("McGnuWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("McGnuWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("McGnuWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPng.setText(QtGui.QApplication.translate("McGnuWindow", "psc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEps.setText(QtGui.QApplication.translate("McGnuWindow", "ps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPdf.setText(QtGui.QApplication.translate("McGnuWindow", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGif.setText(QtGui.QApplication.translate("McGnuWindow", "gif", None, QtGui.QApplication.UnicodeUTF8))
