#!/usr/bin/env python
#
#  Widgets for mcgnuview created with QtCreator. DO NOT EDIT.
#
from PyQt4 import QtCore, QtGui

class Ui_McGnuWindow(object):
    def setupUi(self, McGnuWindow):
        McGnuWindow.setObjectName("McGnuWindow")
        McGnuWindow.resize(403, 276)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(McGnuWindow.sizePolicy().hasHeightForWidth())
        McGnuWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(McGnuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gbxMonitors = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbxMonitors.sizePolicy().hasHeightForWidth())
        self.gbxMonitors.setSizePolicy(sizePolicy)
        self.gbxMonitors.setObjectName("gbxMonitors")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbxMonitors)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lstvMonitors = QtGui.QListWidget(self.gbxMonitors)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstvMonitors.sizePolicy().hasHeightForWidth())
        self.lstvMonitors.setSizePolicy(sizePolicy)
        self.lstvMonitors.setObjectName("lstvMonitors")
        self.verticalLayout_2.addWidget(self.lstvMonitors)
        self.verticalLayout_5.addWidget(self.gbxMonitors)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxOptions = QtGui.QGroupBox(self.centralwidget)
        self.gbxOptions.setObjectName("gbxOptions")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbxOptions)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbxLogScale = QtGui.QCheckBox(self.gbxOptions)
        self.cbxLogScale.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxLogScale.setObjectName("cbxLogScale")
        self.verticalLayout_4.addWidget(self.cbxLogScale)
        self.verticalLayout.addWidget(self.gbxOptions)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gbxSave = QtGui.QGroupBox(self.centralwidget)
        self.gbxSave.setObjectName("gbxSave")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxSave)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnSave = QtGui.QPushButton(self.gbxSave)
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout_3.addWidget(self.btnSave)
        self.btnCloseAll = QtGui.QPushButton(self.gbxSave)
        self.btnCloseAll.setObjectName("btnCloseAll")
        self.verticalLayout_3.addWidget(self.btnCloseAll)
        self.verticalLayout.addWidget(self.gbxSave)
        self.horizontalLayout.addLayout(self.verticalLayout)
        McGnuWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(McGnuWindow)
        self.statusBar.setObjectName("statusBar")
        McGnuWindow.setStatusBar(self.statusBar)
        self.actionOpen = QtGui.QAction(McGnuWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(McGnuWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(McGnuWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPng = QtGui.QAction(McGnuWindow)
        self.actionPng.setObjectName("actionPng")
        self.actionEps = QtGui.QAction(McGnuWindow)
        self.actionEps.setObjectName("actionEps")
        self.actionPdf = QtGui.QAction(McGnuWindow)
        self.actionPdf.setObjectName("actionPdf")
        self.actionGif = QtGui.QAction(McGnuWindow)
        self.actionGif.setObjectName("actionGif")

        self.retranslateUi(McGnuWindow)
        QtCore.QMetaObject.connectSlotsByName(McGnuWindow)

    def retranslateUi(self, McGnuWindow):
        McGnuWindow.setWindowTitle(QtGui.QApplication.translate("McGnuWindow", "McGnuplot", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxMonitors.setTitle(QtGui.QApplication.translate("McGnuWindow", "Click to plot", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxOptions.setTitle(QtGui.QApplication.translate("McGnuWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxLogScale.setText(QtGui.QApplication.translate("McGnuWindow", "Log scale (l)", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxSave.setTitle(QtGui.QApplication.translate("McGnuWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("McGnuWindow", "Save png", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCloseAll.setText(QtGui.QApplication.translate("McGnuWindow", "Close All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("McGnuWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("McGnuWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("McGnuWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPng.setText(QtGui.QApplication.translate("McGnuWindow", "psc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEps.setText(QtGui.QApplication.translate("McGnuWindow", "ps", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPdf.setText(QtGui.QApplication.translate("McGnuWindow", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGif.setText(QtGui.QApplication.translate("McGnuWindow", "gif", None, QtGui.QApplication.UnicodeUTF8))
