#!/bin/sh
if [ -z ${DISPLAY+x} ];
then
    echo "DISPLAY variable is unset! X11 support is needed to continue!";
else
    echo
    echo apt-get\'ing the dependencies using sudo:
    echo
    sudo apt-get -y install git cmake gcc gfortran mingw-w64 gfortran-mingw-w64 flex bison build-essential mingw-w64-x86-64-dev wine64 dos2unix nsis libz-mingw-w64-dev

    mkdir /tmp/innosetup
    cd /tmp/innosetup
    wget https://jrsoftware.org/download.php/is.exe
    wine ./is.exe
fi
