---
abstract: 'Tk - a Graphical User Interface Toolkit'
author:
  - 'nick@ing-simmons.net (Nick Ing-Simmons)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  Test::More: 0
resources:
  repository: http://github.com/eserte/perl-tk
version: 804.03
