/* Generated by Interface Builder */

#import <objc/Object.h>
#import "PGView.h"
#import "pgvListener.h"
#import <appkit/NXCursor.h>

@interface Dispatch:Object
{
      id    infoPanel;

      Listener *myListener;
      NXCursor *crossCursor;
      PGView   *curView;
      BOOL     qdrawing;
      int      iwtype;
}

- showInfo:sender;
- newLand:sender;
- newPort:sender;
- print:sender;

@end
