/* Generated by Interface Builder */

#import <appkit/View.h>
#import <appkit/NXCursor.h>
#import <objc/Storage.h>

@interface PGView:View
{
      Storage     *psdata;
      NXCoord     prevw, prevh;
      int         lwtype;
      DPSContext  ctxt;
      int         iflush, nbuf, nplot;
}

- initFrame:(const NXRect *) frameRect;
- drawSelf:(const NXRect *) rects :(int)rectCount;

- pgplotDefs;

- beginp;
- flush;
- gettype: (int *) iptype;
- getwind: (int *) ixdim  by: (int *) iydim
      color: (int *) icol  scale: (double *) dmag;
- pscode: (char *) cbuf;
- readcursor: (NXPoint *) aPoint char: (int *) ichar
      cursor: (NXCursor *) crossCursor;

@end
