#  Copyright (c) 1990-1994 The Regents of the University of California.
#  Copyright (c) 1994-1996 Sun Microsystems, Inc.
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#

=head1 NAME

Tk::Frame - Create and manipulate Frame widgets

=for category  Tk Widget Classes

=head1 SYNOPSIS

S<    >I<$frame> = I<$parent>-E<gt>B<Frame>(?I<options>?);

=head1 STANDARD OPTIONS

B<-borderwidth>	B<-highlightbackground>	B<-highlightthickness>	B<-takefocus>
B<-class>	B<-highlightcolor>	B<-relief>
B<-cursor>

See L<Tk::options> for details of the standard options.

=head1 WIDGET-SPECIFIC OPTIONS

=over 4

=item Name:	B<background>

=item Class:	B<Background>

=item Switch:	B<-background>

This option is the same as the standard B<background> option
except that its value may also be specified as an undefined value.
In this case, the widget will display no background or border, and
no colors will be consumed from its colormap for its background
and border.

=item Name:	B<colormap>

=item Class:	B<Colormap>

=item Switch:	B<-colormap>

Specifies a colormap to use for the window.
The value may be either B<new>, in which case a new colormap is
created for the window and its children, or the name of another
window (which must be on the same screen and have the same visual
as $widget), in which case the new window will use the colormap
from the specified window.
If the B<colormap> option is not specified, the new window
uses the same colormap as its parent.
This option may not be changed with the B<configure>
method.

=item Name:	B<container>

=item Class:	B<Container>

=item Switch:	B<-container>

The value must be a boolean.  If true, it means that this window will
be used as a container in which some other application will be embedded
(for example, a Tk toplevel can be embedded using the B<-use> option).
The window will support the appropriate window manager protocols for
things like geometry requests.  The window should not have any
children of its own in this application.
This option may not be changed with the B<configure>
method.

=item Name:	B<height>

=item Class:	B<Height>

=item Switch:	B<-height>

Specifies the desired height for the window in any of the forms
acceptable to B<Tk_GetPixels>.
If this option is less than or equal to zero then the window will
not request any size at all.

=item Name:	B<visual>

=item Class:	B<Visual>

=item Switch:	B<-visual>

Specifies visual information for the new window in any of the
forms accepted by B<Tk_GetVisual>.
If this option is not specified, the new window will use the same
visual as its parent.
The B<visual> option may not be modified with the B<configure>
method.

=item Name:	B<width>

=item Class:	B<Width>

=item Switch:	B<-width>

Specifies the desired width for the window in any of the forms
acceptable to B<Tk_GetPixels>.
If this option is less than or equal to zero then the window will
not request any size at all.

=back

=head1 DESCRIPTION

The B<Frame> method creates a new window (given by the
$widget argument) and makes it into a frame widget.
Additional
options, described above, may be specified on the command line
or in the option database
to configure aspects of the frame such as its background color
and relief.  The B<frame> command returns the
path name of the new window.

A frame is a simple widget.  Its primary purpose is to act as a
spacer or container for complex window layouts.  The only features
of a frame are its background color and an optional 3-D border to make the
frame appear raised or sunken.

=head1 WIDGET METHODS

The B<Frame> method creates a widget object.
This object supports the B<configure> and B<cget> methods
described in L<Tk::options> which can be used to enquire and
modify the options described above.
The widget also inherits all the methods provided by the generic
L<Tk::Widget|Tk::Widget> class.

=head1 BINDINGS

When a new frame is created, it has no default event bindings:
frames are not intended to be interactive.

=head1 KEYWORDS

frame, widget

=cut

