# the name of the target operating system
set(CMAKE_SYSTEM_NAME "Darwin")
set(ARCH   "arm64")

# Commands for running various external tools
set(TOOLS_CC "/usr/bin/clang")
set(TERMINAL "open")
set(BROWSER "open")
set(HDFVIEW "nexpy")
set(MPICC "mpicc.clang")
set(MPILIBDIR "GETPATH(miniconda3/lib)")
set(MPIINCLUDEDIR "GETPATH(miniconda3/include)")
set(OACCFLAGS "-ta:multicore -DOPENACC")
set(GSLFLAGS "-IGETPATH(miniconda3/include) -Wl,-rpath,GETPATH(miniconda3/lib) -LGETPATH(miniconda3/lib) -lgsl -lgslcblas")
set(XRLFLAGS "-IGETPATH(miniconda3/include) -Wl,-rpath,GETPATH(miniconda3/lib) -LGETPATH(miniconda3/lib) -lxrl")
set(MPIRUN "mpirun")
set(MPILIB "mpi")
set(NEXUSLIB "GETPATH(miniconda3/lib)")
set(NEXUSINCLUDE "GETPATH(miniconda3/include/nexus)")
set(MCCODE_CFLAGS "-g -O2 -DNDEBUG -lm -std=c99")
set(EDITOR "open")
