
=head1 NAME

Tk::Submethods - add aliases for tk sub-commands

=for pm Tk/Submethods.pm

=for category Implementation

=head1 SYNOPSIS

  use Tk::Submethods ( 'command1' => [qw(sub1 sub2 sub3)],
                       'command2' => [qw(sub1 sub2 sub3)]);

=head1 DESCRIPTION

Creates C<-E<gt>commandSub(...)> as an alias for C<-E<gt>command('sub',...)>
e.g. C<-E<gt>grabRelease> for C<-E<gt>grab('release')>.

For each command/subcommand pair this creates a closure with command
and subcommand as bound lexical variables and assigns a reference to this
to a 'glob' in the callers package.

Someday the sub-commands may be created directly in the C code.

=cut

