#!/usr/bin/arch -x86_64 /bin/bash
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi



./3rdparty/sync.sh

# This is an app bundle being built, but non-relocatable.
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/
./mkdist mcstas-app $1 support/MacOSX/McCode.app/ "" mac "" -- OSXapp

# For the actual mcstas part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/
# 64-bit Mac OS
WORK=`pwd`

if [ ! -f Mambaforge-$(uname)-$(uname -m).sh ]; then
    # Download and embed a miniconda
    echo
    echo "*********************************************************"
    echo "* Downloading a miniconda3 for your app                 *"
    echo "*********************************************************"
    echo
    sleep 3
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
fi
echo "*********************************************************"
echo "* Embedding miniconda3 in your app                      *"
echo "*********************************************************"
chmod a+x Mambaforge-$(uname)-$(uname -m).sh
./Mambaforge-$(uname)-$(uname -m).sh -b -p $MCINSTALL_PREFIX/mcstas/$1/miniconda3/

# Run conda to install the dependencies
echo
echo "*********************************************************"
echo "* Downloading python dependencies to embedded miniconda *"
echo "*********************************************************"
echo

export PATH=$MCINSTALL_PREFIX/mcstas/$1/miniconda3/bin:$PATH


mamba update mamba -y
mamba install mamba conda-build -y
mamba install cmake openmpi compilers gsl pyaml ply matplotlib numpy tornado scipy pillow pyqtgraph pyqt nomkl qscintilla2 nexusformat nexpy hdf5 -y
mamba clean --all -y
cd $WORK


./mkdist mcstas $1 "" "" mac "" -- OSXapp
./mkdist mcstas-comps $1 "" "" mac "" -- OSXapp
./mkdist mcstas-tools-perl $1 tools/Legacy-Perl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac "" -- OSXapp
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" mac "" -- OSXapp
./mkdist mcstas-tools-matlab-mcdisplay $1 tools/matlab/mcdisplay/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcplot-svg $1 tools/Python/mcplot/svg/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcresplot $1 tools/Python/mcresplot/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-matplotlib $1 tools/Python/mcdisplay/matplotlib/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-mantid $1 tools/Python/mcdisplay/mantid_xml/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdisplay-cad $1 tools/Python/mcdisplay/cad/ "" mac "" -- OSXapp
./mkdist mcstas-tools-python-mcdoc $1 tools/Python/mcdoc/ "" mac "" -- OSXapp
./mkdist mcstas-clusterscripts $1 tools/cluster-scripts/ "" mac "" -- OSXapp
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" mac "" -- OSXapp

cd 3rdparty/mcpl
if [ -d build ]; then
    rm -rf build
fi
mkdir -p build; cd build
cmake -DCMAKE_INSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/ ..
make install
cd $WORK

cd 3rdparty/ncrystal
if [ -d build ]; then
    rm -rf build
fi
mkdir -p build; cd build
cmake -DCMAKE_INSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/ ..
make install
cd $WORK

cd 3rdparty/nexus-code
if [ -d build ]; then
    rm -rf build
fi
mkdir -p build; cd build
cmake -DCMAKE_INSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/ -DHDF5_ROOT=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/miniconda3/ -DCMAKE_MACOSX_RPATH=ON -DCMAKE_INSTALL_RPATH=/Applications/McStas-$1.app/Contents/Resources/mcstas/$1/lib  ..
make install
cd $WORK

# Copy in the mpicc snippets
cp support/MacOSX/mpicc-wrappers/* $MCINSTALL_PREFIX/mcstas/$1/bin

export MCINSTALL_PREFIX=/Applications/McStas-$1.app/Contents/Resources/

cd $WORK
# Generate mcdoc pages
$MCINSTALL_PREFIX/mcstas/$1/miniconda3/bin/python $MCINSTALL_PREFIX/mcstas/$1/tools/Python/mcdoc/mcdoc.py -i

# Hack to make openmpi from the conda env available on Big Sur and later
ln -s $MCINSTALL_PREFIX/mcstas/$1/miniconda3/bin/mpi* $MCINSTALL_PREFIX/mcstas/$1/bin/

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McStas-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McStas-$1.app/Contents/Resources/mcstas/$1/environment McStas-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    mv dist mcstas-$1
    mkdir dist
    tar cfz dist/mcstas-$1_x86_64.tgz mcstas-$1
    cp INSTALL-McStas-3.x/macOS/README.md dist
    echo A tgz of your app is now located in the dist folder
    rm -rf mcstas-$1
else
    ln -s /Applications/McStas-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



