#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated
THIRDPARTY=`ls 3rdparty | grep -v patches`
cd 3rdparty

cd -

./3rdparty/sync.sh


for MODULE in `echo $THIRDPARTY`
do
    if [ -d "3rdparty/patches/${MODULE}" ]; then
	echo Making McCode cmake modules available for $MODULE
        rsync -avz cmake/ 3rdparty/${MODULE}/cmake
	echo Applying McCode patches to 3rdparty/${MODULE}
	cp -rp 3rdparty/patches/${MODULE}/* 3rdparty/${MODULE}/
    fi
done
WORK=`pwd`

# 64-bit
./mkdist mcxtrace $1 "" "" linux64 "" -- src
./mkdist mcxtrace-comps $1 "" "" linux64 "" -- src
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" linux64 "" -- src
./mkdist mcxtrace-tools-matlab-mxdisplay $1 tools/matlab/mcdisplay/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mccodelib $1 tools/Python/mccodelib/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxplot-svg $1 tools/Python/mcplot/svg/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxdisplay-cad $1 tools/Python/mcdisplay/cad/ "" linux64 "" -- src
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" linux64 "" -- src
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" linux64 "" -- src
./mkdist mcxtrace-tools-python-mxdoc $1 tools/Python/mcdoc/ "" linux64 "" -- src

export MCINSTALL_PREFIX=/usr/local/mcxtrace/$1
./mkdist mcxtrace-mcpl $1 3rdparty/mcpl-package "" linux64 "" -- src
./mkdist mcxtrace-ncrystal $1 3rdparty/ncrystal-package "" linux64 "" -- src

#build metapackages?
if [ "x$2" != "x" ]; then
  cd meta-pkgs/src

  outfile=mcxtrace-${1}-UNIX-src.tar
  if [ -e $outfile ]; then
    rm $outfile;
  fi
  if [ -e ${outfile}.gz ]; then
    rm ${outfile}.gz;
  fi

  ln -s ../../dist ${outfile%.tar}
  echo  ${outfile%.tar}

  for subpkg in `ls ${outfile%.tar}/mcxtrace*-${1}-src.tar.gz`
  do
    tar -h -rf $outfile $subpkg
  done
  tar -tf $outfile
  gzip $outfile
  rm mcxtrace-${1}-UNIX-src
  cp $WORK/INSTALL-McXtrace-3.x/Linux/src/README.md $WORK/dist
fi
