#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated
THIRDPARTY=`ls 3rdparty | grep -v patches`
cd 3rdparty

cd -

./3rdparty/sync.sh


for MODULE in `echo $THIRDPARTY`
do
    if [ -d "3rdparty/patches/${MODULE}" ]; then
	echo Making McCode cmake modules available for $MODULE
        rsync -avz cmake/ 3rdparty/${MODULE}/cmake
	echo Applying McCode patches to 3rdparty/${MODULE}
	cp -rp 3rdparty/patches/${MODULE}/* 3rdparty/${MODULE}/
    fi
done

WORK=`pwd`

# From 2.1 onwards, let McStas reside in /usr/share on Debian-like systems
export MCINSTALL_PREFIX=/usr/share/

# 32-bit
./mkdist mcstas $1 "" "" deb32 "" -- deb
./mkdist mcstas-comps $1 "" "" deb32 "" -- deb
./mkdist mcstas-tools-matlab-mcplot $1 tools/matlab/mcplot/ "" deb32 "" -- deb
./mkdist mcstas-tools-matlab-mcdisplay $1 tools/matlab/mcdisplay/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcplot-svg $1 tools/Python/mcplot/svg/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcresplot $1 tools/Python/mcresplot/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcrun $1 tools/Python/mcrun/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcgui $1 tools/Python/mcgui/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mccodelib $1 tools/Python/mccodelib/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcdisplay-mantid $1 tools/Python/mcdisplay/mantid_xml/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcdisplay-cad $1 tools/Python/mcdisplay/cad/ "" deb32 "" -- deb
./mkdist mcstas-clusterscripts $1 tools/cluster-scripts/ "" deb32 "" -- deb
./mkdist mcstas-manuals $1 docpkg/manuals/mcstas/ "" deb32 "" -- deb
./mkdist mcstas-tools-python-mcdoc $1 tools/Python/mcdoc/ "" deb32 "" -- deb

./mkdist mcstas-mcpl $1 3rdparty/mcpl-package "" deb32 "" -- deb
./mkdist mcstas-ncrystal $1 3rdparty/ncrystal-package "" deb32 "" -- deb

#build metapackages?
if [ "x$2" != "x" ]; then
  cd meta-pkgs/deb

  for controlfile in `ls control.mcstas*`
  do
    sed -i.bak s/@VERSION@/${1}/g $controlfile
    equivs-build $controlfile
    mv $controlfile.bak $controlfile
  done

  mv $WORK/meta-pkgs/deb/mcstas-suite*${1}*.deb $WORK/dist
  cp $WORK/INSTALL-McStas-3.x/Linux/debian/README.md $WORK/dist
fi
