#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated

./3rdparty/sync.sh

WORK=`pwd`

# 64-bit
./mkdist mcxtrace $1 "" "" rpm64 "" -- rpm
./mkdist mcxtrace-comps $1 "" "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-matlab-mxdisplay $1 tools/matlab/mcdisplay/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mccodelib $1 tools/Python/mccodelib/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-svg $1 tools/Python/mcplot/svg/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" rpm64 "" -- rpm
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" rpm64 "" -- rpm
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" rpm64 "" -- rpm
./mkdist mcxtrace-tools-python-mxdoc $1 tools/Python/mcdoc/ "" rpm64 "" -- rpm
./mkdist mcxtrace-mcpl $1 3rdparty/mcpl-package "" rpm64 "" -- rpm

#build metapackages?
if [ "x$2" != "x" ]; then
  ./support/rpm/miniconda3/prepare.sh $1
  ./mkdist mcxtrace-miniconda3 $1 support/rpm/miniconda3/ "" rpm64 "" -- rpm
  cd meta-pkgs/rpm-centos

  for controlfile in `ls mcxtrace-*.spec`
  do
    sed -i.bak s/@VERSION@/${1}/g $controlfile
    rpmbuild -bb --target x86_64 $controlfile
    mv $controlfile.bak $controlfile
  done
  mv $HOME/rpmbuild/RPMS/x86_64/mcxtrace-suite-*rpm $WORK/dist
  cp $WORK/INSTALL-McXtrace/Linux/centos/README.md $WORK/dist
fi
