#!/bin/sh
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

# Ensure our 3rd party modules are in place and updated
THIRDPARTY=`ls 3rdparty | grep -v patches`
cd 3rdparty

cd -

./3rdparty/sync.sh  


for MODULE in `echo $THIRDPARTY`
do
    if [ -d "3rdparty/patches/${MODULE}" ]; then
	echo Making McCode cmake modules available for $MODULE
        rsync -avz cmake/ 3rdparty/${MODULE}/cmake
	echo Applying McCode patches to 3rdparty/${MODULE}
	cp -rp 3rdparty/patches/${MODULE}/* 3rdparty/${MODULE}/
    fi
done

WORK=`pwd`

# 64-bit
./mkdist mcxtrace $1 "" "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-comps $1 "" "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-matlab-mxdisplay $1 tools/matlab/mcdisplay/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxcodelib $1 tools/Python/mccodelib/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxplot-svg $1 tools/Python/mcplot/svg/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxdisplay-cad $1 tools/Python/mcdisplay/cad/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" rpm64-fedora "" -- rpm
./mkdist mcxtrace-tools-python-mxdoc $1 tools/Python/mcdoc/ "" rpm64-fedora "" -- rpm

export MCINSTALL_PREFIX=/usr/local/mcxtrace/$1
./mkdist mcxtrace-mcpl $1 3rdparty/mcpl-package "" rpm64-fedora "" -- rpm

#build metapackages?
if [ "x$2" != "x" ]; then
  cd meta-pkgs/rpm

  for controlfile in `ls mcxtrace-suite-python.spec`
  do
    sed -i.bak s/@VERSION@/${1}/g $controlfile
    rpmbuild -bb --target x86_64 $controlfile
    mv $controlfile.bak $controlfile
  done
  mv $HOME/rpmbuild/RPMS/x86_64/mcxtrace-suite-*rpm $WORK/dist
  cp $WORK/INSTALL-McXtrace/Linux/centos/README.md $WORK/dist
fi
