#!/bin/bash
export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$(python3 -c "import os;print(os.cpu_count())")}

if [ "x$1" = "x" ]; then
    # No arguments
    echo Please provide one argument,e.g : $0 2.0
    exit 1;
fi

export WORK=`pwd`
# Ensure our 3rd party modules are in place and updated
THIRDPARTY=`ls 3rdparty | grep -v patches`
cd 3rdparty

cd -

./3rdparty/sync.sh


for MODULE in `echo $THIRDPARTY`
do
    if [ -d "3rdparty/patches/${MODULE}" ]; then
	echo Making McCode cmake modules available for $MODULE
        rsync -avz cmake/ 3rdparty/${MODULE}/cmake
	echo Applying McCode patches to 3rdparty/${MODULE}
	cp -rp 3rdparty/patches/${MODULE}/* 3rdparty/${MODULE}/
    fi
done

# This is an app bundle being built, but non-relocatable.
export MCINSTALL_PREFIX=/Applications/McXtrace-$1.app/
./mkdist mcxtrace-app $1 support/MacOSX/McCode.app/ "" mac "" -- OSXapp

# For the actual mcxtrace part, the packages need a 'deep' PREFIX
export MCINSTALL_PREFIX=/Applications/McXtrace-$1.app/Contents/Resources/
# 64-bit Mac OS
./mkdist mcxtrace $1 "" "" mac "" -- OSXapp
./mkdist mcxtrace-comps $1 "" "" mac "" -- OSXapp
./mkdist mcxtrace-tools-perl $1 tools/Legacy-Perl/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-perl-cmdline $1 tools/Legacy-Perl-cmdline/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-matlab-mxplot $1 tools/matlab/mcplot/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-matlab-mxdisplay $1 tools/matlab/mcdisplay/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxplot-pyqtgraph $1 tools/Python/mcplot/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxplot-matplotlib $1 tools/Python/mcplot/matplotlib/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxrun $1 tools/Python/mcrun/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxdoc $1 tools/Python/mcdoc/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxgui $1 tools/Python/mcgui/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mcodelib $1 tools/Python/mccodelib/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxdisplay-webgl $1 tools/Python/mcdisplay/webgl/ "" mac "" -- OSXapp
./mkdist mcxtrace-tools-python-mxdisplay-pyqtgraph $1 tools/Python/mcdisplay/pyqtgraph/ "" mac "" -- OSXapp
./mkdist mcxtrace-clusterscripts $1 tools/cluster-scripts/ "" mac "" -- OSXapp
./mkdist mcxtrace-manuals $1 docpkg/manuals/mcxtrace/ "" mac "" -- OSXapp

WORK=`pwd`

cd 3rdparty/mcpl
if [ -d build ]; then
    rm -rf build
fi
mkdir -p build; cd build
cmake -DCMAKE_INSTALL_PREFIX=/Applications/McXtrace-$1.app/Contents/Resources/mcxtrace/$1/ ..
make install
cd $WORK

if [ ! -f Mambaforge-$(uname)-$(uname -m).sh ]; then
    # Download and embed a miniconda
    echo
    echo "*********************************************************"
    echo "* Downloading a miniconda3 for your app                 *"
    echo "*********************************************************"
    echo
    sleep 3
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
fi
echo "*********************************************************"
echo "* Embedding miniconda3 in your app                      *"
echo "*********************************************************"
chmod a+x Mambaforge-$(uname)-$(uname -m).sh
./Mambaforge-$(uname)-$(uname -m).sh -b -p $MCINSTALL_PREFIX/mcxtrace/$1/miniconda3/

# Run conda to install the dependencies
echo
echo "*********************************************************"
echo "* Downloading python dependencies to embedded miniconda *"
echo "*********************************************************"
echo
export PATHBAK=$PATH
export PATH=$MCINSTALL_PREFIX/mcxtrace/$1/miniconda3/bin:$PATH

mamba update mamba -y
mamba install mamba conda-build -y
mamba install openmpi gsl pyaml ply matplotlib numpy tornado scipy pillow pyqtgraph qscintilla2 pyqt nomkl nexusformat nexpy hdf5 autoconf automake libtool -y
mamba clean --all -y

cd $WORK

cd 3rdparty/nexus-code
if [ -d build ]; then
    rm -rf build
fi
mkdir -p build; cd build
cmake -DCMAKE_INSTALL_PREFIX=/Applications/McXtrace-$1.app/Contents/Resources/mcxtrace/$1/ -DHDF5_ROOT=/Applications/McXtrace-$1.app/Contents/Resources/mcxtrace/$1/miniconda3/ -DCMAKE_MACOSX_RPATH=ON -DCMAKE_INSTALL_RPATH=/Applications/McXtrace-$1.app/Contents/Resources/mcxtrace/$1/lib  ..
make install
cd $WORK

cd 3rdparty/xraylib
autoreconf -i
./configure --prefix=/Applications/McXtrace-$1.app/Contents/Resources/mcxtrace/$1/
make install
cd $WORK

export PATH=$PATHBAK
# Copy in the mpicc snippets
cp support/MacOSX/mpicc-wrappers/* $MCINSTALL_PREFIX/mcxtrace/$1/bin

export MCINSTALL_PREFIX=/Applications/McXtrace-$1.app/Contents/Resources/

cd $WORK
# Generate mcdoc pages
$MCINSTALL_PREFIX/mcxtrace/$1/miniconda3/bin/python $MCINSTALL_PREFIX/mcxtrace/$1/tools/Python/mxdoc/mcdoc.py -i

# Hack to make openmpi from the conda env available on Big Sur and later
ln -s $MCINSTALL_PREFIX/mcxtrace/$1/miniconda3/bin/mpi* $MCINSTALL_PREFIX/mcxtrace/$1/bin/

mkdir -p dist
# Move the App bundle back to the dist - or keep it in /Applications?
if [ "x$2" = "x" ]; then
    mv /Applications/McXtrace-$1.app dist
    ln -s /Applications dist/
    cd dist
    ln -s McXtrace-$1.app/Contents/Resources/mcxtrace/$1/environment McXtrace-$1-environment.command
    cd ..
    cp support/MacOSX/Check-dependencies/* dist
    mv dist mcxtrace-$1
    mkdir dist
    tar cfz dist/mcxtrace-$1_x86_64.tgz mcxtrace-$1
    cp INSTALL-McXtrace-3.x/macOS/README.md dist
    echo A tgz of your app is now located in the dist folder
    rm -rf mcxtrace-$1
else
    ln -s /Applications/McXtrace-$1.app dist/
    echo Your app is now located in /Applications \(link available in the dist folder\)
fi



