#!/usr/bin/env bash

# Ensure our 3rd party modules are in place and updated
git submodule init
git submodule update

WORK=`pwd`

export MCINSTALL_PREFIX=$WORK/testbuilds/
rm -rf $MCINSTALL_PREFIX/mcstas/2.x-test/
rm -rf dist/*
mkdir -p buildlogs

# 64-bit debian
echo "*********************************************************"
echo "* Building mcstas                                       *"
echo "*********************************************************"
./mkdist mcstas 2.x-test "" "" deb64 "" -- justinst &> buildlogs/mcstas_deb.log
echo "- Done! Build log available in buildlogs/mcstas_deb.log"
echo
echo "*********************************************************"
echo "* Building mcstas-comps                                 *"
echo "*********************************************************"
./mkdist mcstas-comps 2.x-test "" "" deb64 "" -- justinst &> buildlogs/mcstas-comps_deb.log
echo "- Done! Build log available in buildlogs/mcstas-comps_deb.log"
echo
echo "*********************************************************"
echo "* Building Perl-based commandline tools                 *"
echo "*********************************************************"
./mkdist mcstas-tools-perl-cmdline 2.x-test tools/Legacy-Perl-cmdline/ "" deb64 "" -- justinst &> buildlogs/mcstas-tools_deb.log
echo "- Done! Build log available in buildlogs/mcstas-tools_deb.log"
echo

export MCSTAS=$MCINSTALL_PREFIX/mcstas/2.x-test
export MCSTAS_TOOLS=$MCSTAS/tools/Perl/
export PATH=$MCSTAS/miniconda3/bin:$MCSTAS/bin:$PATH

cd buildlogs
echo "*********************************************************"
echo "* Running integration test with GCC                      *"
echo "*********************************************************"
export MCSTAS_CC=gcc
mcrun.pl --test &> mcstas-test_deb_gcc.log
echo "- Done! Test log available in buildlogs/mcstas-test_deb_gcc.log"
echo "*********************************************************"
echo "* Running integration test with CLANG                   *"
echo "*********************************************************"
export MCSTAS_CC=clang
export MCSTAS_CFLAGS="-g -lm -O2 -stdlib=libc++"
mcrun.pl --test &> mcstas-test_deb_clang.log
echo "- Done! Test log available in buildlogs/mcstas-test_deb_clang.log"
