#!/usr/bin/env bash

# Ensure our 3rd party modules are in place and updated
git submodule init
git submodule update

WORK=`pwd`

export MCINSTALL_PREFIX=$WORK/testbuilds/
rm -rf $MCINSTALL_PREFIX/mcxtrace/1.x-test/
rm -rf dist/*
mkdir -p buildlogs

# 64-bit debian
echo "*********************************************************"
echo "* Building mcxtrace                                     *"
echo "*********************************************************"
./mkdist mcxtrace 1.x-test "" "" deb64 "" -- justinst &> buildlogs/mcxtrace_deb.log
echo "- Done! Build log available in buildlogs/mcxtrace_deb.log"
echo
echo "*********************************************************"
echo "* Building mcxtrace-comps                               *"
echo "*********************************************************"
./mkdist mcxtrace-comps 1.x-test "" "" deb64 "" -- justinst &> buildlogs/mcxtrace-comps_deb.log
echo "- Done! Build log available in buildlogs/mcxtrace-comps_deb.log"
echo
echo "*********************************************************"
echo "* Building Perl-based commandline tools                 *"
echo "*********************************************************"
./mkdist mcxtrace-tools-perl-cmdline 1.x-test tools/Legacy-Perl-cmdline/ "" deb64 "" -- justinst &> buildlogs/mcxtrace-tools_deb.log
echo "- Done! Build log available in buildlogs/mcxtrace-tools_deb.log"
echo

export MCXTRACE=$MCINSTALL_PREFIX/mcxtrace/1.x-test
export MCXTRACE_TOOLS=$MCXTRACE/tools/Perl/
export PATH=$MCXTRACE/miniconda3/bin:$MCXTRACE/bin:$PATH

cd buildlogs
echo "*********************************************************"
echo "* Running integration test with GCC                      *"
echo "*********************************************************"
export MCXTRACE_CC_OVERRIDE=gcc
mxrun.pl --test &> mcxtrace-test_deb_gcc.log
echo "- Done! Test log available in buildlogs/mcxtrace-test_deb_gcc.log"
echo "*********************************************************"
echo "* Running integration test with CLANG                   *"
echo "*********************************************************"
export MCXTRACE_CC_OVERRIDE=clang
export MCXTRACE_CFLAGS="-g -lm -O2 -stdlib=libc++"
mxrun.pl --test &> mcxtrace-test_deb_clang.log
echo "- Done! Test log available in buildlogs/mcxtrace-test_deb_clang.log"
