#!/bin/sh
export BUILDDIR="/build/@MCCODE_TARNAME@-@MCCODE_VERSION@"
export SRCDIR="/build/@MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir"
export MACHINETYPE=`uname -m`

apt-get -y --force-yes install perl-tk pdl gcc libc6-dev g77 libx11-dev xorg-dev libxt-dev lintian

rm -rf /build/*
rm -rf /usr/local/lib/*
rm -rf /usr/local/pgplot

echo Performing @MCCODE_STRING@ install to /usr/local

cd /build
tar xzf /root/@MCCODE_TARNAME@-@MCCODE_VERSION@-src.tar.gz
mv @MCCODE_TARNAME@-@MCCODE_VERSION@ @MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir
cd @MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir

make
make install

./configure

make install-pgplot

./configure

cd /build
rm -rf /usr/local/lib/mcstas.*



mkdir ${BUILDDIR}
mkdir ${BUILDDIR}/DEBIAN
mkdir ${BUILDDIR}/usr/
mkdir ${BUILDDIR}/usr/local/
mkdir ${BUILDDIR}/usr/local/lib
mkdir ${BUILDDIR}/usr/share
mkdir ${BUILDDIR}/usr/share/doc
mkdir ${BUILDDIR}/usr/share/doc/mcstas

cp -rp /usr/local/bin ${BUILDDIR}/usr/local
cp -rp /usr/local/lib/* ${BUILDDIR}/usr/local/lib
cp -rp /usr/local/pgplot ${BUILDDIR}/usr/local

cp @MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir/deb/control ${BUILDDIR}/DEBIAN
cp @MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir/deb/prerm ${BUILDDIR}/DEBIAN
cp @MCCODE_TARNAME@-@MCCODE_VERSION@-srcdir/deb/postinst ${BUILDDIR}/DEBIAN

find ${BUILDDIR} -type d -exec chmod 0755 \{\} \;

chmod 0755 ${BUILDDIR}/DEBIAN/prerm
chmod 0755 ${BUILDDIR}/DEBIAN/postinst

cp ${SRCDIR}/CHANGES ${BUILDDIR}/usr/share/doc/mcstas/changelog
cp ${SRCDIR}/CHANGES ${BUILDDIR}/usr/share/doc/mcstas/changelog.Debian
cp ${SRCDIR}/COPYING ${BUILDDIR}/usr/share/doc/mcstas/copyright

dpkg-deb --build @MCCODE_TARNAME@-@MCCODE_VERSION@

mv @MCCODE_TARNAME@-@MCCODE_VERSION@.deb @MCCODE_TARNAME@-@MCCODE_VERSION@-${MACHINETYPE}.deb

rm -rf $BUILDDIR


