''' UI classes. 

Some autogenerated (do not edit).

@author: jaga
'''
from PyQt4 import QtCore, QtGui


''' View class containing all windows and dialogs.
ALL explicit ui widget updates MUST be handled by this class
'''
class McView(object):
    def __init__(self):
        # create main window
        self.__mw = McMainWindow()
        self.mwui = self.__mw.ui
        self.mwui.lblInstrument.setText("")
        
    def showMainWindow(self):
        self.__mw.show()
        
    ''' Update UI data
    '''
    def updateLabels(self, labels):
        self.mwui.lblInstrument.setText(labels[0])
        
    def updateWorkDir(self, workDir):
        self.mwui.lblWorkDir.setText(workDir)
        
    def updateStatus(self, text=''):
        self.mwui.statusbar.showMessage(text)
        
    def updateLog(self, text=''):
        self.mwui.textBrowser.append(text)
        
    def updateSimState(self, state=[]):
        self.mwui.actionRS.setEnabled(state[0]=='True')
        self.mwui.actionCS.setEnabled(state[1]=='True')
        self.mwui.actionPS.setEnabled(state[2]=='True')
        
    ''' UI actions
    '''
    def showOpenInstrumentDlg(self, lookDir):
        dlg = QtGui.QFileDialog()
        dlg.setDirectory(lookDir)
        dlg.setNameFilter("mcstas instruments (*.instr)");
        if dlg.exec_():
            return dlg.selectedFiles()[0]
    
    def showChangeWorkDirDlg(self, lookDir):
        dlg = QtGui.QFileDialog()
        dlg.setFileMode(QtGui.QFileDialog.Directory)
        dlg.setDirectory(lookDir)
        if dlg.exec_():
            return dlg.selectedFiles()[0]

    def showStartSimDialog(self, params):
        dlg = McStartSimDialog()
        dlg.createParamsWidgets(params)
        if dlg.exec_():
            return dlg.getValues()
        else: 
            return None, None


''' Main Window widgets class
'''
class McMainWindow(QtGui.QMainWindow):
    def __init__(self, parent=None):
        super(McMainWindow, self).__init__(parent)
        self.ui =  Ui_MainWindow()
        self.ui.setupUi(self)


''' Start simulation widgets class
'''
class McStartSimDialog(QtGui.QDialog):
    def __init__(self, parent=None):
        super(McStartSimDialog, self).__init__(parent)
        self.ui = Ui_dlgStartSim()
        self.ui.setupUi(self)
        self.ui.btnStart.clicked.connect(self.accept)
        self.ui.btnCancel.clicked.connect(self.reject)
        
    def getValues(self):
        # simulation or trace option
        p0 = None
        if self.ui.cbxSimTrace.currentIndex() == 0:
            p0 = SimTraceEnum.SIM
        else:
            p0 = SimTraceEnum.TRACE
        
        # neutron count
        p1 = self.ui.edtNeutronCnt.text()
        
        # steps
        p2 = self.ui.edtSteps.text()
        
        # gravity
        p3 = self.ui.checkBox.checkState()
        
        # clustering option 
        p4 = None
        if self.ui.cbxClustering.currentIndex() == 0:
            p4 = ClusteringEnum.SINGLE
        if self.ui.cbxClustering.currentIndex() == 1:
            p4 = ClusteringEnum.MPI
        if self.ui.cbxClustering.currentIndex() == 2:
            p4 = ClusteringEnum.SSH
            
        # clustring option
        p5 = self.ui.edtNodes.text()
        
        fixed_params =[p0, p1, p2, p3, p4, p5]
        
        # get values of text boxes matching params
        params = []
        for w in self.__wParams:
            p = []
            p.append(str(w[0].text()).rstrip(':'))
            p.append(str(w[1].text()))
            params.append(p)
        
        return fixed_params, params
    
    __wParams = []
    def createParamsWidgets(self, params):
        # clear the grid
        grd = self.ui.gridLayout
        for i in reversed(range(grd.count())): 
            grd.itemAt(i).widget().setParent(None)
            
        self.__wParams = None
        self.__wParams = []
        # insert custom params widgets
        i = -1
        x = 0
        y = 0
        for p in params:
            name = QtCore.QString(p[0])
            value = QtCore.QString(p[1])
            
            i = i + 1
            x = i % 6
            y = i / 6
            
            lbl = QtGui.QLabel(self.ui.gbxGrid)
            lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
            lbl.setObjectName("lbl" + name)
            lbl.setText(name + ':')
            self.ui.gridLayout.addWidget(lbl, y, x, 1, 1)
            
            i = i + 1
            x = i % 6
            
            edt = QtGui.QLineEdit(self.ui.gbxGrid)
            edt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
            edt.setObjectName("edt" + name)
            edt.setText(value)
            self.ui.gridLayout.addWidget(edt, y, x, 1, 1)
            
            self.__wParams.append([lbl, edt])
class SimTraceEnum:
    SIM = 0
    TRACE = 1
class ClusteringEnum:
    SINGLE = 0 
    MPI = 1
    SSH = 2
                

''' Main window ui widget setup.
Auto-generated view created with QtCreator.
Generate from .ui source with pyside-uic. 
Do not edit.
'''
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setToolTip("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxInstrument = QtGui.QGroupBox(self.centralwidget)
        self.gbxInstrument.setObjectName("gbxInstrument")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbxInstrument)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblInstrument = QtGui.QLabel(self.gbxInstrument)
        self.lblInstrument.setObjectName("lblInstrument")
        self.gridLayout.addWidget(self.lblInstrument, 2, 1, 1, 1)
        self.tbtnInstrument = QtGui.QToolButton(self.gbxInstrument)
        self.tbtnInstrument.setObjectName("tbtnInstrument")
        self.gridLayout.addWidget(self.tbtnInstrument, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.btnRun = QtGui.QPushButton(self.gbxInstrument)
        self.btnRun.setObjectName("btnRun")
        self.gridLayout.addWidget(self.btnRun, 2, 4, 1, 1)
        self.btnPlot = QtGui.QPushButton(self.gbxInstrument)
        self.btnPlot.setObjectName("btnPlot")
        self.gridLayout.addWidget(self.btnPlot, 2, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.gbxInstrument)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbxMessages = QtGui.QGroupBox(self.centralwidget)
        self.gbxMessages.setObjectName("gbxMessages")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxMessages)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbxOutput = QtGui.QTabWidget(self.gbxMessages)
        self.tbxOutput.setObjectName("tbxOutput")
        self.tabMcgui = QtGui.QWidget()
        self.tabMcgui.setObjectName("tabMcgui")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabMcgui)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txtbrwMcgui = QtGui.QTextBrowser(self.tabMcgui)
        self.txtbrwMcgui.setObjectName("txtbrwMcgui")
        self.verticalLayout_4.addWidget(self.txtbrwMcgui)
        self.tbxOutput.addTab(self.tabMcgui, "")
        self.tabSim = QtGui.QWidget()
        self.tabSim.setObjectName("tabSim")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabSim)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txtbrwSim = QtGui.QTextBrowser(self.tabSim)
        self.txtbrwSim.setObjectName("txtbrwSim")
        self.verticalLayout_5.addWidget(self.txtbrwSim)
        self.tbxOutput.addTab(self.tabSim, "")
        self.verticalLayout_3.addWidget(self.tbxOutput)
        self.horizontalLayout_2.addWidget(self.gbxMessages)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_instrument = QtGui.QAction(MainWindow)
        self.actionOpen_instrument.setObjectName("actionOpen_instrument")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRun_Simulation = QtGui.QAction(MainWindow)
        self.actionRun_Simulation.setObjectName("actionRun_Simulation")
        self.actionCompile_Instrument = QtGui.QAction(MainWindow)
        self.actionCompile_Instrument.setObjectName("actionCompile_Instrument")
        self.actionMcstas_User_Manual = QtGui.QAction(MainWindow)
        self.actionMcstas_User_Manual.setObjectName("actionMcstas_User_Manual")
        self.actionMcstas_Web_Page = QtGui.QAction(MainWindow)
        self.actionMcstas_Web_Page.setObjectName("actionMcstas_Web_Page")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRS = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("run-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../GIMP/run-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionRS.setIcon(icon)
        self.actionRS.setObjectName("actionRS")
        self.actionCS = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("compile-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../../GIMP/compile-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCS.setIcon(icon1)
        self.actionCS.setObjectName("actionCS")
        self.actionPS = QtGui.QAction(MainWindow)
        self.actionPS.setObjectName("actionPS")
        self.actionMcstas_Component_Manual = QtGui.QAction(MainWindow)
        self.actionMcstas_Component_Manual.setObjectName("actionMcstas_Component_Manual")
        self.actionChange_Working_Dir = QtGui.QAction(MainWindow)
        self.actionChange_Working_Dir.setObjectName("actionChange_Working_Dir")
        self.actionNew_Instrument = QtGui.QAction(MainWindow)
        self.actionNew_Instrument.setObjectName("actionNew_Instrument")
        self.menuFile.addAction(self.actionNew_Instrument)
        self.menuFile.addAction(self.actionOpen_instrument)
        self.menuFile.addAction(self.actionChange_Working_Dir)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSimulation.addAction(self.actionRun_Simulation)
        self.menuSimulation.addAction(self.actionCompile_Instrument)
        self.menuHelp.addAction(self.actionMcstas_User_Manual)
        self.menuHelp.addAction(self.actionMcstas_Component_Manual)
        self.menuHelp.addAction(self.actionMcstas_Web_Page)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tbxOutput.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mcgui-py", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxInstrument.setTitle(QtGui.QApplication.translate("MainWindow", "Instrument:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInstrument.setText(QtGui.QApplication.translate("MainWindow", "<Instrument file>", None, QtGui.QApplication.UnicodeUTF8))
        self.tbtnInstrument.setToolTip(QtGui.QApplication.translate("MainWindow", "Browse instrument...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbtnInstrument.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRun.setText(QtGui.QApplication.translate("MainWindow", "Run...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxMessages.setTitle(QtGui.QApplication.translate("MainWindow", "Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxOutput.setTabText(self.tbxOutput.indexOf(self.tabMcgui), QtGui.QApplication.translate("MainWindow", "mcgui", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxOutput.setTabText(self.tbxOutput.indexOf(self.tabSim), QtGui.QApplication.translate("MainWindow", "Simulations", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_instrument.setText(QtGui.QApplication.translate("MainWindow", "Open Instrument...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Run Simulation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompile_Instrument.setText(QtGui.QApplication.translate("MainWindow", "Compile Instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMcstas_User_Manual.setText(QtGui.QApplication.translate("MainWindow", "mcstas User Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMcstas_Web_Page.setText(QtGui.QApplication.translate("MainWindow", "mcstas Web Page", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRS.setText(QtGui.QApplication.translate("MainWindow", "RS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRS.setToolTip(QtGui.QApplication.translate("MainWindow", "Compile/Run simulation...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCS.setText(QtGui.QApplication.translate("MainWindow", "CS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCS.setToolTip(QtGui.QApplication.translate("MainWindow", "Compile instrument", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPS.setText(QtGui.QApplication.translate("MainWindow", "PS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPS.setToolTip(QtGui.QApplication.translate("MainWindow", "Plot results...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMcstas_Component_Manual.setText(QtGui.QApplication.translate("MainWindow", "mcstas Component Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_Working_Dir.setText(QtGui.QApplication.translate("MainWindow", "Change Work Dir...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Instrument.setText(QtGui.QApplication.translate("MainWindow", "New Instrument...", None, QtGui.QApplication.UnicodeUTF8))




''' Start simulation dialog widget
Auto-generated view created with QtCreator.
Generate from .ui source with pyside-uic. 
Do not edit.
'''
class Ui_dlgStartSim(object):
    def setupUi(self, dlgStartSim):
        dlgStartSim.setObjectName("dlgStartSim")
        dlgStartSim.resize(504, 386)
        self.verticalLayout_4 = QtGui.QVBoxLayout(dlgStartSim)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxGrid = QtGui.QGroupBox(dlgStartSim)
        self.gbxGrid.setObjectName("gbxGrid")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbxGrid)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblGridDummy = QtGui.QLabel(self.gbxGrid)
        self.lblGridDummy.setObjectName("lblGridDummy")
        self.gridLayout.addWidget(self.lblGridDummy, 0, 0, 1, 1)
        self.edtGridDummy2 = QtGui.QLineEdit(self.gbxGrid)
        self.edtGridDummy2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtGridDummy2.setObjectName("edtGridDummy2")
        self.gridLayout.addWidget(self.edtGridDummy2, 0, 3, 1, 1)
        self.lblGridDummy2 = QtGui.QLabel(self.gbxGrid)
        self.lblGridDummy2.setObjectName("lblGridDummy2")
        self.gridLayout.addWidget(self.lblGridDummy2, 0, 2, 1, 1)
        self.lblGridDummy3 = QtGui.QLabel(self.gbxGrid)
        self.lblGridDummy3.setObjectName("lblGridDummy3")
        self.gridLayout.addWidget(self.lblGridDummy3, 0, 4, 1, 1)
        self.edtGridDummy = QtGui.QLineEdit(self.gbxGrid)
        self.edtGridDummy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtGridDummy.setObjectName("edtGridDummy")
        self.gridLayout.addWidget(self.edtGridDummy, 0, 1, 1, 1)
        self.edtGridDummy3 = QtGui.QLineEdit(self.gbxGrid)
        self.edtGridDummy3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtGridDummy3.setObjectName("edtGridDummy3")
        self.gridLayout.addWidget(self.edtGridDummy3, 0, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.gbxGrid)
        self.gbxSim = QtGui.QGroupBox(dlgStartSim)
        self.gbxSim.setObjectName("gbxSim")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxSim)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbxSimTrace = QtGui.QComboBox(self.gbxSim)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxSimTrace.sizePolicy().hasHeightForWidth())
        self.cbxSimTrace.setSizePolicy(sizePolicy)
        self.cbxSimTrace.setObjectName("cbxSimTrace")
        self.cbxSimTrace.addItem("")
        self.cbxSimTrace.addItem("")
        self.gridLayout_2.addWidget(self.cbxSimTrace, 1, 0, 1, 1)
        self.cbxClustering = QtGui.QComboBox(self.gbxSim)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxClustering.sizePolicy().hasHeightForWidth())
        self.cbxClustering.setSizePolicy(sizePolicy)
        self.cbxClustering.setObjectName("cbxClustering")
        self.cbxClustering.addItem("")
        self.cbxClustering.addItem("")
        self.cbxClustering.addItem("")
        self.gridLayout_2.addWidget(self.cbxClustering, 6, 0, 1, 1)
        self.edtNeutronCnt = QtGui.QLineEdit(self.gbxSim)
        self.edtNeutronCnt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtNeutronCnt.setObjectName("edtNeutronCnt")
        self.gridLayout_2.addWidget(self.edtNeutronCnt, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gbxSim)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 6, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.gbxSim)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 4, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gbxSim)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 1, 1, 1)
        self.label = QtGui.QLabel(self.gbxSim)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gbxSim)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.edtSteps = QtGui.QLineEdit(self.gbxSim)
        self.edtSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtSteps.setObjectName("edtSteps")
        self.gridLayout_2.addWidget(self.edtSteps, 2, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gbxSim)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 3, 1, 1, 1)
        self.edtNodes = QtGui.QLineEdit(self.gbxSim)
        self.edtNodes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edtNodes.setObjectName("edtNodes")
        self.gridLayout_2.addWidget(self.edtNodes, 6, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.gbxSim)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnStart = QtGui.QPushButton(dlgStartSim)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout_3.addWidget(self.btnStart)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btnCancel = QtGui.QPushButton(dlgStartSim)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_3.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout)

        self.retranslateUi(dlgStartSim)
        QtCore.QMetaObject.connectSlotsByName(dlgStartSim)

    def retranslateUi(self, dlgStartSim):
        dlgStartSim.setWindowTitle(QtGui.QApplication.translate("dlgStartSim", "Start simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxGrid.setTitle(QtGui.QApplication.translate("dlgStartSim", "Instrument parameters (D=floating point, I=integer, S=string):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGridDummy.setText(QtGui.QApplication.translate("dlgStartSim", "lambda (D):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGridDummy2.setText(QtGui.QApplication.translate("dlgStartSim", "R (D):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGridDummy3.setText(QtGui.QApplication.translate("dlgStartSim", "R_curve (D):", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxSim.setTitle(QtGui.QApplication.translate("dlgStartSim", "Simulation:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSimTrace.setItemText(0, QtGui.QApplication.translate("dlgStartSim", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSimTrace.setItemText(1, QtGui.QApplication.translate("dlgStartSim", "Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxClustering.setItemText(0, QtGui.QApplication.translate("dlgStartSim", "No clustering", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxClustering.setItemText(1, QtGui.QApplication.translate("dlgStartSim", "MPI clustering", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxClustering.setItemText(2, QtGui.QApplication.translate("dlgStartSim", "SSH clustering", None, QtGui.QApplication.UnicodeUTF8))
        self.edtNeutronCnt.setText(QtGui.QApplication.translate("dlgStartSim", "1000000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dlgStartSim", "# nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dlgStartSim", "Random seed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgStartSim", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dlgStartSim", "Neutron count:", None, QtGui.QApplication.UnicodeUTF8))
        self.edtSteps.setText(QtGui.QApplication.translate("dlgStartSim", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("dlgStartSim", "Gravity", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStart.setText(QtGui.QApplication.translate("dlgStartSim", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("dlgStartSim", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

