/*******************************************************************************
*
* McStas, version 1.0, released October 26, 1998
*         Maintained by Kristian Nielsen and Kim Lefmann,
*         Risoe National Laboratory, Roskilde, Denmark
*
* Component: 4PI monitor.
*
* Written by:  KL, KN  April 17, 1998
* Modified by: KL      Sept. 22, 1998
*
* Counts ALL neutrons that propagate this far in the instrument, regardless
* of origin or direction. Mostly used for test purposes.
*
* INPUT PARAMETERS:
*
* (none)
*
* OUTPUT PARAMETERS:
*
* Nsum   : Number of neutrons hitting
* psum   : Total weight of neutrons hitting
* p2sum  : Second moment of neutron weights
*
*******************************************************************************/


DEFINE COMPONENT Monitor_4PI
DEFINITION PARAMETERS ()
SETTING PARAMETERS ()
OUTPUT PARAMETERS(Nsum, psum, p2sum)
STATE PARAMETERS (x,y,z,vx,vy,vz,t,s1,s2,p)
DECLARE
  %{
    int Nsum;
    double psum,p2sum;
  %}
INITIALIZE
  %{
    Nsum = 0;
    psum = 0;
    p2sum = 0;
  %}
TRACE
  %{
    Nsum++;
    psum += p;
    p2sum += p*p;
  %}
FINALLY
  %{
    DETECTOR_OUT(Nsum, psum, p2sum);
  %}
END
