#!/bin/bash

url=http://physics.nist.gov/cgi-bin/ffast/ffast.pl

if [ -z "$1" ]
then 
  echo "what material are you trying to get data for? please supply atomic number."
  echo "usage: get_xray_db_data ATOMNO [output file]"
fi

Z=$1

range=S

modifiers="?Z=$Z&Formula=&gtype=4&range=$range&lower=0&upper=500&density=&frames=noframes"

tfile=`mktemp --tmpdir get_xray.XXX`

echo $tfile

wget "$url$modifiers" -O $tfile; 
#extract element name from Z
element_symbol=`w3m -T text/html -dump $tfile |head -c 2` 
echo writing output to $element_symbol.txt

w3m -T text/html -dump $tfile |sed '{1,100 s/^[^0-9\n]/#&/}' |sed '{s/^$/#/}' >$element_symbol.txt

rm $tfile
