#  Copyright (c) 1990 The Regents of the University of California.
#  Copyright (c) 1994-1996 Sun Microsystems, Inc.
#  See the file "license.terms" for information on usage and redistribution
#  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
#

=head1 NAME

Tk_MainWindow - find the main window for an application

=for category C Programming

=head1 SYNOPSIS

B<#include E<lt>tk.hE<gt>>

Tk_Window
B<Tk_MainWindow>(I<interp>)

=head1 ARGUMENTS

=over 4

=item Tcl_Interp *interp (in/out)

Interpreter associated with the application.

=back

=head1 DESCRIPTION

If I<interp> is associated with a Tk application then B<Tk_MainWindow>
returns the application's main window.
If there is no Tk application associated with I<interp> then
B<Tk_MainWindow> returns NULL and leaves an error message
in I<interp-E<gt>result>.

=head1 KEYWORDS

application, main window
