#!/usr/local/bin/perl -w
use Tk;
my $mw = MainWindow->new;
my $dialog = $mw->Dialog(-text => 'Hello There');
warn <<EOF;
**********************************************************************
* NOTE: iconify does not work anymore --- iconifying transient
*       windows is not allowed
**********************************************************************
EOF
foreach $meth (qw(Show withdraw deiconify iconify Popup))
 {
  $mw->Button(-text => "\u$meth", -command => [$meth => $dialog])->pack(-side => 'left');
 }
$|  = 1;
select STDERR;
$|  = 1;
select STDOUT;
# $^D = 8;
MainLoop;